#!/usr/bin/env python3
"""Automated tests for Mode B settlement maps (diagram skill).

Obtains every SCRIPTED map in pool/ through the gate cache (feature 026: a
verified gen-cache hit skips GENERATION only; any doubt - or GATE_NO_CACHE=1 -
regenerates) and runs the full check_village gate over the resulting manifest.
This pins the whole Mode B process: any change to the settlement/ package, a
scripted engine, or a spec that breaks an invariant (no overlaps, every field
ringed, households-consistent house counts, channels anchored, no label
overlaps, ...) fails here - checking is never cached.

THE HAND-AUTHORED POOL IS FROZEN (GM 2026-08-16; migration-plan.md "The accepted
trade"): legacy maps are permanent exhibits - never regenerated, never re-gated -
so this sweep covers scripted maps only, and engine changes are free to alter
behavior without holding 19 deprecated compositions byte-identical. poolmaps.py
is the classification; the ratchet below keeps every pool gen accounted for.

Works under pytest OR standalone:
    python3 -m pytest test_villages.py -q     # from the diagram skill directory
    python3 test_villages.py                  # no pytest required
"""

import glob
import json
import os
import runpy
import sys

import pytest

from l7r.diagram import check_village
from l7r.diagram.pipeline import gencache, poolmaps

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # the skill root; the tests live one level down in tests/
POOL = os.path.join(HERE, "pool")


GENERATORS = sorted(g for g in glob.glob(os.path.join(POOL, "*", "*.gen.py")) if poolmaps.classify(g) == "scripted")


def test_every_pool_gen_is_classified():
    """THE RATCHET for poolmaps.classify: every `.gen.py` in the pool is a swept scripted map, a
    declared Mode A compound, or a declared FROZEN legacy map - anything else is a map nobody
    checks. The scripted detection is SOURCE TEXT (which engine the gen imports), so a gen built on
    a NEW engine module is invisible to it - the "a check that never runs looks exactly like a
    check that passes" failure applied to a whole map. It happened on 2026-08-11: the scripted demo
    maps (then in `pool/experiments/`, since dissolved into `pool/hamlets/`) import `hamletgen`
    rather than `settlement`, so four maps sat in the pool being regenerated by nobody and gated by
    nothing, with the sweep entirely green. Both declared lists are also checked AGAINST the pool,
    so a rename or deletion cannot leave a stale name behind."""
    gens = glob.glob(os.path.join(POOL, "*", "*.gen.py"))
    unknown = sorted(os.path.basename(g) for g in gens if poolmaps.classify(g) == "unknown")
    assert not unknown, (
        f"pool gen(s) that are neither scripted, compound, nor frozen legacy: {unknown} - a map in "
        f"the pool that no test regenerates is a map with no gate. If it is built on a new scripted "
        f"engine module, add that module to poolmaps.SCRIPTED_ENGINES; if it is a Mode A compound "
        f"plan, add it to poolmaps.COMPOUND_GENS. Hand-authoring a new Mode B map is DEPRECATED "
        f"(migration-plan.md) and the frozen legacy list is closed - extending it takes a GM decision."
    )
    present = {os.path.basename(g) for g in gens}
    stale = sorted((poolmaps.LEGACY_FROZEN_GENS | poolmaps.COMPOUND_GENS) - present)
    assert not stale, f"declared in poolmaps.py but not present in the pool (renamed or deleted?): {stale}"


def test_poolmaps_classifies_each_kind(tmp_path):
    assert poolmaps.classify(os.path.join(POOL, "hamlets", "sawada.gen.py")) == "scripted"
    assert poolmaps.classify(os.path.join(POOL, "hamlets", "moritono.gen.py")) == "legacy"
    assert poolmaps.classify(os.path.join(POOL, "magistracies", "county-magistracy-example.gen.py")) == "compound"
    stray = tmp_path / "stray.gen.py"
    stray.write_text("print('no engine import at all')\n")
    assert poolmaps.classify(str(stray)) == "unknown"


# HOW LONG A GEN IS ALLOWED TO TAKE (CPU seconds). WHY (GM 2026-08-03, right after the incident
# that motivates it): Minami's gen silently became a 45+ MINUTE grind when the paddy-well rule
# landed - `_well_ground_clear` re-scanned all 927 drawn basins and ~580 watercourse segments per
# candidate seat - and nothing failed; sessions just waited it out, or timed out and misdiagnosed
# it (see CLAUDE.md "Gate and sweep timings"). A budget turns "mysteriously slow" into a loud,
# early, NAMED failure. It is aimed at that pathological class - a per-candidate scan of static
# geometry, which this engine keeps regrowing - not at 20% drift, so another session adding a
# legitimate rule should never have to argue with it.
#
# CALIBRATE AGAINST THE GATE, NOT A SOLO RUN. These asserts fire inside `make done`, i.e. under
# `pytest -n auto` (22 workers here), where a gen's own CPU TIME inflates 2-4x through cache and
# memory-bandwidth contention - process CPU time is immune to WAITING for a core, not to needing
# more cycles for the same work. Budgets tuned on solo timings duly went off on their first gate
# run (kikuta: 10.9s solo, 36.2s under the gate, against a 30s budget). So each entry is ~4x its
# SOLO measurement, i.e. roughly 1.5x its worst observed under-gate time. A map that legitimately
# outgrows its entry gets a bigger one WITH the reason recorded, the same discipline as a waiver.
GEN_TIME_BUDGET_S = 45.0  # default: an ordinary map measures 1-7s solo, comfortably under even inflated
GEN_TIME_BUDGETS = {
    # (The heavy hand-authored maps - minami at 60s, nagahara/tango/kikuta/hoshizora at 50s - had
    # entries here until the 2026-08-16 legacy freeze took them out of the sweep entirely.)
    # THE SCRIPTED HAMLETS (2026-08-12) are slow for a reason that is not the pathological shape this
    # guard exists for, and the reason is inherent rather than a regression: `hamletgen.fit_field`
    # BISECTS a size multiplier against the drawn plot area, carving the whole comb several times per
    # map to land the paddy acreage the household count implies - so one map is several maps' worth of
    # carve. Passing `build_comb` its principled `grain` of 2.0 (see waterfields.py) added a further
    # ~35% on top, measured on Sawada: 14.6s solo at 1.0, 19.8s at 2.0, from the wider ditches and the
    # extra footbridge arithmetic they need. Entries are ~4x the solo measurement, as above.
    "sawada": 80.0,  # ~20s solo - the biggest cohort map, 19 households
    "kashikawa": 65.0,  # ~16s solo
    "inashiro": 50.0,  # ~11s solo
}


def test_a_map_is_immune_to_an_upstream_change_in_the_number_of_random_draws():
    """THE RATCHET for positional/scoped randomness (GM 2026-08-08).

    Generate one map twice - the second time with ONE extra `random.random()` consumed at `meta()`,
    which is what any upstream change that draws differently amounts to - and demand a byte-identical
    manifest. Before the discipline landed this moved 13 of a town's 71 manifest keys, including
    houses, wells, gardens, groves and 2,754 tree crowns; the visible cost was a farm shed drawn on a
    garden 700 px from anything that had changed.

    The subject was a hand-authored TOWN (hoshizora) until the 2026-08-16 legacy freeze, because a
    town exercises both mechanisms at once: position-seeded attributes (a house's rake, its wall
    colour, its kura) and scoped phases (ring, pack, frontage, pasture, grove, wells, farmsteads).
    Legacy gens are never run by the suite now, so the subject is a large SCRIPTED hamlet - it
    holds the attribute mechanism and the farmstead/well/grove scopes, but not the urban scopes
    (ring, pack, frontage). When the town tier converts to scripted generation, move the subject
    to a scripted town: a hamlet alone would not have held the original line.
    """
    import random

    from l7r.diagram import settlement

    gen = os.path.join(HERE, "pool", "hamlets", "kashikawa.gen.py")

    def once(perturb):
        orig = settlement.Settlement.meta

        def patched(self, *a, **kw):
            r = orig(self, *a, **kw)
            for _ in range(perturb):
                random.random()
            return r

        settlement.Settlement.meta = patched
        os.environ["DIAGRAM_SKIP_RENDER"] = "1"
        try:
            runpy.run_path(gen, run_name="__main__")
        finally:
            settlement.Settlement.meta = orig
            del os.environ["DIAGRAM_SKIP_RENDER"]
        with open(gen[: -len(".gen.py")] + ".json") as fh:
            return fh.read()

    clean = once(0)
    assert once(1) == clean, "an upstream change in the number of random draws re-rolled the map - see CLAUDE.md 'RANDOMNESS IS POSITIONAL OR SCOPED'"
    assert once(0) == clean  # ...and leave the committed manifest as the unperturbed run wrote it


def _regen_and_gate(gen):
    """Obtain a map through the gate cache, then run its gate; True if every check passes.

    A verified HIT (feature 026) skips GENERATION only: the entry's stored coverage replays into
    this run, and the check battery below still judges whatever manifest was served. A miss
    regenerates in gencache's coverage-recording subprocess (with DIAGRAM_SKIP_RENDER inside -
    the gate reads the JSON manifest, never the PNG). The budget assert reads the CHILD-measured
    CPU, so it applies exactly when generation actually ran."""
    manifest, how, cpu_s = gencache.gate_obtain(gen)
    if how == "REGENERATED":
        assert cpu_s is not None
        name = os.path.basename(gen)[: -len(".gen.py")]
        budget = GEN_TIME_BUDGETS.get(name, GEN_TIME_BUDGET_S)
        assert cpu_s <= budget or os.environ.get("DIAGRAM_ALLOW_SLOW_GENS") == "1", (
            f"{name}.gen.py took {cpu_s:.1f}s CPU against a {budget:.0f}s budget - it is a SURPRISE that this gen "
            f"takes so long, and the last time one did (Minami, 2026-08-02) it was a 45-minute perf bug that "
            f"nothing flagged. Please consider whether a perf regression landed (the known shape: re-scanning "
            f"static geometry per candidate seat - see CLAUDE.md 'Gate and sweep timings') before anything else. "
            f"If you are CERTAIN perf is fine, rerun with DIAGRAM_ALLOW_SLOW_GENS=1, and raise this map's entry "
            f"in GEN_TIME_BUDGETS with the reason recorded beside it."
        )
    assert os.path.exists(manifest), f"{os.path.basename(gen)} produced no manifest"
    return check_village.main(manifest) == 0


def test_at_least_one_village_exists():
    assert GENERATORS, "no *.gen.py village generators found in pool/"


def test_slow_gen_budget_fires_and_the_override_silences_it(tmp_path, monkeypatch):
    # the guard must be SHOWN to fire (a check that never fires looks exactly like a check that
    # passes): a CPU-burning fake gen against a near-zero budget trips the surprise message, and
    # the documented override lets it through (to then fail on the missing manifest instead,
    # proving the budget assert itself was silenced)
    gen = tmp_path / "snail.gen.py"
    gen.write_text("import time\nt0 = time.process_time()\nwhile time.process_time() - t0 < 0.05:\n    pass\n")
    monkeypatch.setitem(GEN_TIME_BUDGETS, "snail", 0.001)
    # Bypass the cache and keep the snail's entry out of the real .gencache (026): without the
    # bypass the SECOND call would HIT on the entry the first call stored and never reach the
    # budget assert at all - the override's silencing would be untested.
    monkeypatch.setenv("GATE_NO_CACHE", "1")
    monkeypatch.setattr(gencache, "CACHE_DIR", str(tmp_path / "cache"))
    # OWN THE ENVIRONMENT, do not inherit it (2026-08-03): the override is documented for
    # WHOLE-SWEEP use ("rerun with DIAGRAM_ALLOW_SLOW_GENS=1"), and a session that follows that
    # advice silenced the budget for this test too - so the one test proving the guard still has
    # teeth failed precisely when someone used the guard as designed, turning the escape hatch into
    # a guaranteed red gate. The fire-half must be measured with the override OFF regardless of how
    # the sweep was invoked.
    monkeypatch.delenv("DIAGRAM_ALLOW_SLOW_GENS", raising=False)
    with pytest.raises(AssertionError, match="SURPRISE"):
        _regen_and_gate(str(gen))
    monkeypatch.setenv("DIAGRAM_ALLOW_SLOW_GENS", "1")
    with pytest.raises(AssertionError, match="produced no manifest"):
        _regen_and_gate(str(gen))


def _channels_under_plots(svgpath):
    """SVG-level z-order audit: every field channel (the #6C9CBE supply / #7C9EB0 drain strokes)
    must draw OVER the paddy plots it crosses. A channel whose midpoint lies inside a plot polygon
    that appears LATER in the document is painted over - the invisible-ditch-net defect (GM
    2026-07-21: Hoshizora's canals "rendering below the rice paddies"; also Hikari-no-sato's
    first comb under its second comb's plots, and the cities' residual 2nd-fan hole). This is
    deliberately an SVG test, not a manifest check: scatter/paint order is not manifest-recorded,
    same as the per-tuft skips. Returns the covered channels as (x, y) midpoints."""
    import re

    with open(svgpath) as fh:
        svg = fh.read()
    plots = []
    for m in re.finditer(r'<polygon points="([^"]+)" fill="#[0-9A-Fa-f]{6}" stroke="#[0-9A-Fa-f]{6}" stroke-width="2"', svg):
        plots.append((m.start(), [tuple(map(float, p.split(","))) for p in m.group(1).split()]))
    covered = []
    for m in re.finditer(r'<path d="M([^"]+)" fill="none" stroke="#(?:6C9CBE|7C9EB0)"', svg):
        coords = [tuple(map(float, p.split(","))) for p in m.group(1).replace(" L", ";").split(";")]
        mid = coords[len(coords) // 2]
        if any(pos > m.start() and check_village.point_in_poly(mid[0], mid[1], pts) for pos, pts in plots):
            covered.append((round(mid[0]), round(mid[1])))
    return covered


def _typical_cell_acres(svgpath, ftpx):
    """Real-feet area of the TYPICAL leveled paddy cell (a bund-stroked plot polygon), taking the mean
    of the 45th-75th percentile band (the regular interior cells, above the edge wedges). Pins the
    ~0.05-acre paddy calibration (GM 2026-07-22, see settlements.md 'Paddy cell size'). SVG-measured,
    not a manifest gate, because villages do not record plot_polys - same tier as the ditch z-order audit."""
    import re
    import statistics

    with open(svgpath) as fh:
        svg = fh.read()

    def _sl(poly):
        return abs(sum(poly[i][0] * poly[(i + 1) % len(poly)][1] - poly[(i + 1) % len(poly)][0] * poly[i][1] for i in range(len(poly)))) / 2

    from l7r.diagram.waterfields import AZE

    # comb plots carry the AZE bund stroke at aze_w's 2-decimal width (the patchwork field() path
    # formats its width to 1 decimal, so \d+\.\d\d selects exactly the comb cells, as the old
    # literal stroke-width="2" did) - keyed to the AZE constant so a recolor cannot silently
    # de-match this parser again (the 2026-07-24 aze recolor broke the old hardcoded signature)
    areas = sorted(
        _sl([tuple(map(float, p.split(","))) for p in m.group(1).split()]) * ftpx * ftpx
        for m in re.finditer(rf'<polygon points="([^"]+)" fill="#[0-9A-Fa-f]{{6}}" stroke="{AZE}" stroke-width="\d+\.\d\d"', svg)
    )
    if len(areas) < 8:
        return None
    band = areas[int(len(areas) * 0.45) : int(len(areas) * 0.75)]
    return statistics.mean(band) / 43560


# one test per village (not one loop over all): a failure names its map directly, and a
# parallel runner (pytest-xdist) can spread the regens instead of serializing them in one test
@pytest.mark.parametrize("gen", GENERATORS, ids=[os.path.basename(g) for g in GENERATORS])
def test_village_passes_gate(gen):
    assert _regen_and_gate(gen), f"{os.path.basename(gen)} failed the gate"
    svg = gen[: -len(".gen.py")] + ".svg"
    covered = _channels_under_plots(svg)
    assert not covered, (
        f"{os.path.basename(gen)}: {len(covered)} field channel(s) painted UNDER a later plot at {covered[:5]} - route the comb net through the LATE water block (field_channel late=True; see settlement._water)"
    )
    # PADDY CELL SIZE stays in the calibrated real-feet band (GM 2026-07-22). Every valley-paddy comb map
    # (all villages + cities) and the two HILL-RICE archetype demos - contour_terraces (Tanada) and
    # ribbon_valley (Yatsuda), whose steps/bands are now split into leveled cells - hold to it; the band
    # spans plot_texture's small_irregular->large_block knobs (~0.036-0.0675) plus slop and, above all,
    # catches a regression back to the old hand-set ~0.13 ac (or the old field-wide terrace/ribbon bands).
    # The polder / dike-pond archetypes are DELIBERATELY larger (Buck's ~1 mu parcels, 0.4-0.6 ha ponds -
    # true-scale per settlements.md line ~102), so they are excluded, not held to the leveled-cell target.
    with open(gen[: -len(".gen.py")] + ".json") as _fh:
        manifest = json.load(_fh)
    meta = manifest.get("meta", {})
    _valley = meta.get("scale") in ("village", "city")
    _hill_rice = meta.get("field_archetype") in ("contour_terraces", "ribbon_valley")
    if _valley or _hill_rice:
        cell = _typical_cell_acres(svg, meta.get("ftpx") or 2)
        assert cell is not None and 0.030 <= cell <= 0.072, (
            f"{os.path.basename(gen)}: typical paddy cell {cell:.3f} ac is outside the calibrated 0.030-0.072 band (see settlements.md 'Paddy cell size')"
        )


if __name__ == "__main__":
    rc = 0
    for g in GENERATORS:
        ok = _regen_and_gate(g)
        print(("PASS " if ok else "FAIL ") + os.path.basename(g))
        rc |= 0 if ok else 1
    sys.exit(rc)
