"""Unit tests for the SCRIPTED hamlet generator, one module per source submodule.

The DIVISION OF LABOR with the rest of the suite is deliberate and worth knowing before adding a
test here. The four demo maps in `pool/hamlets/` are regenerated by `test_villages.py` on every
run and put through the whole gate, so the STAGES - the drawing, the placing, the manifest - are
covered end to end there, on real output, by the same machinery that covers every other pool map.
What this package covers is everything a map cannot: the pure derivations (sizing, rolls, geometry
helpers), the branches the four demos do not happen to take, and the failure modes that must stay
loud (a household count outside the tier band, a nonsense compass quarter).

So: a rule about SHAPE goes here; a rule about a MAP belongs in the pool. Which MODULE it goes in
mirrors `hamletgen/` exactly - a test for `hamletgen/ways.py` lives in `test_ways.py`.
"""

import os
import sys

SKILL = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if SKILL not in sys.path:  # so the tests import the engine whatever the rootdir
    sys.path.insert(0, SKILL)  # pragma: no cover - under pytest the skill dir is already on the path
