#!/usr/bin/env python3
"""Classify every pool `*.gen.py` map for the tools that walk the pool.

The single source of truth (imported by `test_villages.py`, `regen.py` and `cache_audit.py`) for
which pool maps are LIVE and which are museum pieces. The answer changed on 2026-08-16, when the GM
froze the hand-authored pool (see migration-plan.md "The accepted trade"), and three tools each had
their own idea of what the pool contains - this module is so they cannot drift apart.

- **scripted** - generated by a scripted-generation engine (`SCRIPTED_ENGINES`). LIVE: regenerated
  and gated by the `test_villages.py` sweep, re-rolled freely by engine changes, audited by
  `cache_audit.py`.
- **legacy** - a hand-authored Mode B map, FROZEN: its committed .json/.svg/.png are permanent
  exhibits (still browsable in `pool/index.html`), never regenerated and never re-gated, so
  evolving placement rules and checks cost nothing on maps whose authoring process is deprecated.
  A frozen map's defects against NEW rules are expected and are not bugs; the map gets fixed by
  CONVERSION, not retrofit. The list is CLOSED - hand-authoring a new Mode B map is deprecated, so
  extending it takes an explicit GM decision.
- **compound** - a Mode A compound plan (magistracies). Not a settlement at all: no manifest for
  the gate, out of the migration's scope (migration-plan.md section 1), still hand-authored by
  design and still actively maintained.
- **unknown** - anything else. `test_villages.py`'s ratchet fails the suite by name on these,
  because a map in the pool that no test regenerates is a map with no gate.
"""

from __future__ import annotations

import os

# Scripted-generation engine modules. A gen that imports one of these is a LIVE scripted map; add
# each new engine (a future village/town generator) here and its maps join the sweep automatically.
SCRIPTED_ENGINES = ("hamletgen",)

# Mode A compound gens, by basename rather than detected, so a gen that is neither a known
# compound nor a recognized scripted map is a loud "unknown" instead of a silent omission.
COMPOUND_GENS = frozenset(
    {
        "hayakawa-magistracy.gen.py",
        "ubame-magistracy.gen.py",
        "county-magistracy-example.gen.py",
        "ochiba-magistracy.gen.py",
        "ochiba-roundtrip-test.gen.py",
    }
)

# The frozen hand-authored Mode B pool, in full (GM 2026-08-16). CLOSED: do not add to this list
# without the GM's say-so - a new settlement map should be scripted instead.
LEGACY_FROZEN_GENS = frozenset(
    {
        # hamlets
        "akagahara.gen.py",
        "enokida.gen.py",
        "honda.gen.py",
        "ikegami.gen.py",
        "kuwabata.gen.py",
        "moritono.gen.py",
        "shimizu.gen.py",
        "tanada.gen.py",
        "yatsuda.gen.py",
        # villages
        "hikari-no-sato.gen.py",
        "hoshigaoka.gen.py",
        "kikuta.gen.py",
        "ueda.gen.py",
        # towns
        "hirameki.gen.py",
        "hoshizora.gen.py",
        "ubame.gen.py",
        # provincial cities
        "minami.gen.py",
        "nagahara.gen.py",
        "tango.gen.py",
    }
)


def classify(gen: str) -> str:
    """'scripted' | 'legacy' | 'compound' | 'unknown' for a pool gen path.

    Scripted maps are detected by which engine the gen imports (the same source-text heuristic the
    sweep always used - see the 2026-08-11 incident in test_villages.py's ratchet: a gen built on
    an engine module nobody listed is invisible, so new engines must be added to SCRIPTED_ENGINES).
    Legacy and compound maps are explicit closed lists, because both sets are finished: nothing new
    is ever supposed to join them without a human deciding so.
    """
    base = os.path.basename(gen)
    if base in COMPOUND_GENS:
        return "compound"
    with open(gen) as fh:
        src = fh.read()
    if any(f"{m} import" in src or f"import {m}" in src for m in SCRIPTED_ENGINES):
        return "scripted"
    if base in LEGACY_FROZEN_GENS:
        return "legacy"
    return "unknown"
