#!/usr/bin/env python3
"""Automated tests for Mode B settlement maps (diagram skill).

Regenerates every village in pool/ from its generator and runs the full
check_village gate over the resulting manifest. This pins the whole Mode B
process: any change to settlement.py or a village spec that breaks an invariant
(no overlaps, every field ringed, households-consistent house counts, channels
anchored, no label overlaps, ...) fails here.

Works under pytest OR standalone:
    python3 -m pytest test_villages.py -q     # from the diagram skill directory
    python3 test_villages.py                  # no pytest required
"""

import glob
import json
import os
import runpy
import sys
import time

import pytest

import check_village

HERE = os.path.dirname(os.path.abspath(__file__))
POOL = os.path.join(HERE, "pool")


def _is_village_gen(gen):
    """A Mode B VILLAGE gen builds on the settlement engine (`settlement.py`) and emits a JSON manifest the
    check_village gate reads. Mode A COMPOUND gens (built on `compound.py`, e.g. ochiba-roundtrip-test) also live
    in pool/ but are hand-plan SVGs with NO village manifest - running one produces nothing to gate (and may
    raise SystemExit from its own `__main__` guard). They are not villages, so this test skips them; they carry
    their own tests. Discriminate by which engine the gen imports (every village gen imports settlement; no
    compound gen does - verified across the pool).

    THE HEURISTIC IS SOURCE TEXT, so a gen built on a NEW Mode B engine module is invisible to it -
    which is the "a check that never runs looks exactly like a check that passes" failure, applied
    to the whole sweep. It happened on 2026-08-11: `pool/experiments/*.gen.py` import `hamletgen`
    rather than `settlement`, so four maps sat in the pool being regenerated by nobody and gated by
    nothing, with the sweep entirely green. Add a new engine module to MODE_B_ENGINES when you write
    one; `test_every_pool_gen_is_swept_or_declared_a_compound` below fails by name if you forget."""
    with open(gen) as fh:
        src = fh.read()
    return any(f"{m} import" in src or f"import {m}" in src for m in MODE_B_ENGINES)


MODE_B_ENGINES = ("settlement", "hamletgen")

# Mode A compound gens: they live in pool/ but emit no village manifest, so the sweep skips them.
# Listed by BASENAME rather than detected, so that a gen which is neither a known compound nor a
# recognized village gen is a loud failure instead of a silent omission.
COMPOUND_GENS = (
    "hayakawa-magistracy.gen.py",
    "ubame-magistracy.gen.py",
    "county-magistracy-example.gen.py",
    "ochiba-magistracy.gen.py",
    "ochiba-roundtrip-test.gen.py",
)

GENERATORS = sorted(g for g in glob.glob(os.path.join(POOL, "*", "*.gen.py")) if _is_village_gen(g))


def test_every_pool_gen_is_swept_or_declared_a_compound():
    """THE RATCHET for the discriminator above: every `.gen.py` in the pool is either swept as a
    village or explicitly declared a Mode A compound. A gen that is neither is a map nobody checks."""
    unswept = [os.path.basename(g) for g in glob.glob(os.path.join(POOL, "*", "*.gen.py")) if g not in GENERATORS]
    assert not [u for u in unswept if u not in COMPOUND_GENS], (
        f"pool gen(s) matched by neither the village sweep nor COMPOUND_GENS: {sorted(u for u in unswept if u not in COMPOUND_GENS)} - "
        f"a map in the pool that no test regenerates is a map with no gate. If it is built on a new Mode B engine module, add that "
        f"module to MODE_B_ENGINES; if it is a Mode A compound plan, add it to COMPOUND_GENS."
    )


# HOW LONG A GEN IS ALLOWED TO TAKE (CPU seconds). WHY (GM 2026-08-03, right after the incident
# that motivates it): Minami's gen silently became a 45+ MINUTE grind when the paddy-well rule
# landed - `_well_ground_clear` re-scanned all 927 drawn basins and ~580 watercourse segments per
# candidate seat - and nothing failed; sessions just waited it out, or timed out and misdiagnosed
# it (see CLAUDE.md "Gate and sweep timings"). A budget turns "mysteriously slow" into a loud,
# early, NAMED failure. It is aimed at that pathological class - a per-candidate scan of static
# geometry, which this engine keeps regrowing - not at 20% drift, so another session adding a
# legitimate rule should never have to argue with it.
#
# CALIBRATE AGAINST THE GATE, NOT A SOLO RUN. These asserts fire inside `make done`, i.e. under
# `pytest -n auto` (22 workers here), where a gen's own CPU TIME inflates 2-4x through cache and
# memory-bandwidth contention - process CPU time is immune to WAITING for a core, not to needing
# more cycles for the same work. Budgets tuned on solo timings duly went off on their first gate
# run (kikuta: 10.9s solo, 36.2s under the gate, against a 30s budget). So each entry is ~4x its
# SOLO measurement, i.e. roughly 1.5x its worst observed under-gate time. A map that legitimately
# outgrows its entry gets a bigger one WITH the reason recorded, the same discipline as a waiver.
GEN_TIME_BUDGET_S = 45.0  # default: an ordinary map measures 1-7s solo, comfortably under even inflated
GEN_TIME_BUDGETS = {
    # Solo CPU seconds noted per entry, re-measured 2026-08-04 after the second optimization pass
    # (the frozen_terrain well scope, the _fits reach index, the ground-cover grids, and Minami's
    # own label index). Every heavy map has roughly halved AGAIN - the five that need an entry are
    # now within 2x of each other where they used to span 15s to 54s.
    "minami": 60.0,  # ~14.5s solo (21s before the top-up seat memo, 54s three passes ago): the biggest map, and the only one that still needs real headroom
    "nagahara": 50.0,  # ~9s solo (37s)
    "tango": 50.0,  # ~10s solo (24s)
    "kikuta": 50.0,  # ~10s solo (35s): its ground-cover scatter, the pass's first big find
    "hoshizora": 50.0,  # ~10s solo (15s)
}


def test_a_map_is_immune_to_an_upstream_change_in_the_number_of_random_draws():
    """THE RATCHET for positional/scoped randomness (GM 2026-08-08).

    Generate one map twice - the second time with ONE extra `random.random()` consumed at `meta()`,
    which is what any upstream change that draws differently amounts to - and demand a byte-identical
    manifest. Before the discipline landed this moved 13 of a town's 71 manifest keys, including
    houses, wells, gardens, groves and 2,754 tree crowns; the visible cost was a farm shed drawn on a
    garden 700 px from anything that had changed.

    A TOWN is the subject because it exercises both mechanisms at once: position-seeded attributes
    (a house's rake, its wall colour, its kura) and scoped phases (ring, pack, frontage, pasture,
    grove, wells, farmsteads). Hamlets pass on the attributes alone, so they would not hold the line.
    """
    import random

    import settlement

    gen = os.path.join(os.path.dirname(__file__), "pool", "towns", "hoshizora.gen.py")

    def once(perturb):
        orig = settlement.Settlement.meta

        def patched(self, *a, **kw):
            r = orig(self, *a, **kw)
            for _ in range(perturb):
                random.random()
            return r

        settlement.Settlement.meta = patched
        os.environ["DIAGRAM_SKIP_RENDER"] = "1"
        try:
            runpy.run_path(gen, run_name="__main__")
        finally:
            settlement.Settlement.meta = orig
            del os.environ["DIAGRAM_SKIP_RENDER"]
        with open(gen[: -len(".gen.py")] + ".json") as fh:
            return fh.read()

    clean = once(0)
    assert once(1) == clean, "an upstream change in the number of random draws re-rolled the map - see CLAUDE.md 'RANDOMNESS IS POSITIONAL OR SCOPED'"
    assert once(0) == clean  # ...and leave the committed manifest as the unperturbed run wrote it


def _regen_and_gate(gen):
    """Run a village generator, then its gate; return True if every check passes.
    Runs the generator IN-PROCESS (not as a subprocess) so coverage measures settlement.py.
    The gate reads the JSON manifest, never the PNG, so DIAGRAM_SKIP_RENDER skips the resvg
    raster - cheap since the resvg switch, but still pure waste in the test loop."""
    os.environ["DIAGRAM_SKIP_RENDER"] = "1"
    t0 = time.process_time()
    try:
        runpy.run_path(gen, run_name="__main__")
    finally:
        del os.environ["DIAGRAM_SKIP_RENDER"]
    cpu_s = time.process_time() - t0
    name = os.path.basename(gen)[: -len(".gen.py")]
    budget = GEN_TIME_BUDGETS.get(name, GEN_TIME_BUDGET_S)
    assert cpu_s <= budget or os.environ.get("DIAGRAM_ALLOW_SLOW_GENS") == "1", (
        f"{name}.gen.py took {cpu_s:.1f}s CPU against a {budget:.0f}s budget - it is a SURPRISE that this gen "
        f"takes so long, and the last time one did (Minami, 2026-08-02) it was a 45-minute perf bug that "
        f"nothing flagged. Please consider whether a perf regression landed (the known shape: re-scanning "
        f"static geometry per candidate seat - see CLAUDE.md 'Gate and sweep timings') before anything else. "
        f"If you are CERTAIN perf is fine, rerun with DIAGRAM_ALLOW_SLOW_GENS=1, and raise this map's entry "
        f"in GEN_TIME_BUDGETS with the reason recorded beside it."
    )
    manifest = gen[: -len(".gen.py")] + ".json"
    assert os.path.exists(manifest), f"{os.path.basename(gen)} produced no manifest"
    return check_village.main(manifest) == 0


def test_at_least_one_village_exists():
    assert GENERATORS, "no *.gen.py village generators found in pool/"


def test_slow_gen_budget_fires_and_the_override_silences_it(tmp_path, monkeypatch):
    # the guard must be SHOWN to fire (a check that never fires looks exactly like a check that
    # passes): a CPU-burning fake gen against a near-zero budget trips the surprise message, and
    # the documented override lets it through (to then fail on the missing manifest instead,
    # proving the budget assert itself was silenced)
    gen = tmp_path / "snail.gen.py"
    gen.write_text("import time\nt0 = time.process_time()\nwhile time.process_time() - t0 < 0.05:\n    pass\n")
    monkeypatch.setitem(GEN_TIME_BUDGETS, "snail", 0.001)
    # OWN THE ENVIRONMENT, do not inherit it (2026-08-03): the override is documented for
    # WHOLE-SWEEP use ("rerun with DIAGRAM_ALLOW_SLOW_GENS=1"), and a session that follows that
    # advice silenced the budget for this test too - so the one test proving the guard still has
    # teeth failed precisely when someone used the guard as designed, turning the escape hatch into
    # a guaranteed red gate. The fire-half must be measured with the override OFF regardless of how
    # the sweep was invoked.
    monkeypatch.delenv("DIAGRAM_ALLOW_SLOW_GENS", raising=False)
    with pytest.raises(AssertionError, match="SURPRISE"):
        _regen_and_gate(str(gen))
    monkeypatch.setenv("DIAGRAM_ALLOW_SLOW_GENS", "1")
    with pytest.raises(AssertionError, match="produced no manifest"):
        _regen_and_gate(str(gen))


def _channels_under_plots(svgpath):
    """SVG-level z-order audit: every field channel (the #6C9CBE supply / #7C9EB0 drain strokes)
    must draw OVER the paddy plots it crosses. A channel whose midpoint lies inside a plot polygon
    that appears LATER in the document is painted over - the invisible-ditch-net defect (GM
    2026-07-21: Hoshizora's canals "rendering below the rice paddies"; also Hikari-no-sato's
    first comb under its second comb's plots, and the cities' residual 2nd-fan hole). This is
    deliberately an SVG test, not a manifest check: scatter/paint order is not manifest-recorded,
    same as the per-tuft skips. Returns the covered channels as (x, y) midpoints."""
    import re

    with open(svgpath) as fh:
        svg = fh.read()
    plots = []
    for m in re.finditer(r'<polygon points="([^"]+)" fill="#[0-9A-Fa-f]{6}" stroke="#[0-9A-Fa-f]{6}" stroke-width="2"', svg):
        plots.append((m.start(), [tuple(map(float, p.split(","))) for p in m.group(1).split()]))
    covered = []
    for m in re.finditer(r'<path d="M([^"]+)" fill="none" stroke="#(?:6C9CBE|7C9EB0)"', svg):
        coords = [tuple(map(float, p.split(","))) for p in m.group(1).replace(" L", ";").split(";")]
        mid = coords[len(coords) // 2]
        if any(pos > m.start() and check_village.point_in_poly(mid[0], mid[1], pts) for pos, pts in plots):
            covered.append((round(mid[0]), round(mid[1])))
    return covered


def _typical_cell_acres(svgpath, ftpx):
    """Real-feet area of the TYPICAL leveled paddy cell (a bund-stroked plot polygon), taking the mean
    of the 45th-75th percentile band (the regular interior cells, above the edge wedges). Pins the
    ~0.05-acre paddy calibration (GM 2026-07-22, see settlements.md 'Paddy cell size'). SVG-measured,
    not a manifest gate, because villages do not record plot_polys - same tier as the ditch z-order audit."""
    import re
    import statistics

    with open(svgpath) as fh:
        svg = fh.read()

    def _sl(poly):
        return abs(sum(poly[i][0] * poly[(i + 1) % len(poly)][1] - poly[(i + 1) % len(poly)][0] * poly[i][1] for i in range(len(poly)))) / 2

    from waterfields import AZE

    # comb plots carry the AZE bund stroke at aze_w's 2-decimal width (the patchwork field() path
    # formats its width to 1 decimal, so \d+\.\d\d selects exactly the comb cells, as the old
    # literal stroke-width="2" did) - keyed to the AZE constant so a recolor cannot silently
    # de-match this parser again (the 2026-07-24 aze recolor broke the old hardcoded signature)
    areas = sorted(
        _sl([tuple(map(float, p.split(","))) for p in m.group(1).split()]) * ftpx * ftpx
        for m in re.finditer(rf'<polygon points="([^"]+)" fill="#[0-9A-Fa-f]{{6}}" stroke="{AZE}" stroke-width="\d+\.\d\d"', svg)
    )
    if len(areas) < 8:
        return None
    band = areas[int(len(areas) * 0.45) : int(len(areas) * 0.75)]
    return statistics.mean(band) / 43560


# one test per village (not one loop over all): a failure names its map directly, and a
# parallel runner (pytest-xdist) can spread the regens instead of serializing them in one test
@pytest.mark.parametrize("gen", GENERATORS, ids=[os.path.basename(g) for g in GENERATORS])
def test_village_passes_gate(gen):
    assert _regen_and_gate(gen), f"{os.path.basename(gen)} failed the gate"
    svg = gen[: -len(".gen.py")] + ".svg"
    covered = _channels_under_plots(svg)
    assert not covered, (
        f"{os.path.basename(gen)}: {len(covered)} field channel(s) painted UNDER a later plot at {covered[:5]} - route the comb net through the LATE water block (field_channel late=True; see settlement._water)"
    )
    # PADDY CELL SIZE stays in the calibrated real-feet band (GM 2026-07-22). Every valley-paddy comb map
    # (all villages + cities) and the two HILL-RICE archetype demos - contour_terraces (Tanada) and
    # ribbon_valley (Yatsuda), whose steps/bands are now split into leveled cells - hold to it; the band
    # spans plot_texture's small_irregular->large_block knobs (~0.036-0.0675) plus slop and, above all,
    # catches a regression back to the old hand-set ~0.13 ac (or the old field-wide terrace/ribbon bands).
    # The polder / dike-pond archetypes are DELIBERATELY larger (Buck's ~1 mu parcels, 0.4-0.6 ha ponds -
    # true-scale per settlements.md line ~102), so they are excluded, not held to the leveled-cell target.
    with open(gen[: -len(".gen.py")] + ".json") as _fh:
        manifest = json.load(_fh)
    meta = manifest.get("meta", {})
    _valley = meta.get("scale") in ("village", "city")
    _hill_rice = meta.get("field_archetype") in ("contour_terraces", "ribbon_valley")
    if _valley or _hill_rice:
        cell = _typical_cell_acres(svg, meta.get("ftpx") or 2)
        assert cell is not None and 0.030 <= cell <= 0.072, (
            f"{os.path.basename(gen)}: typical paddy cell {cell:.3f} ac is outside the calibrated 0.030-0.072 band (see settlements.md 'Paddy cell size')"
        )


if __name__ == "__main__":
    rc = 0
    for g in GENERATORS:
        ok = _regen_and_gate(g)
        print(("PASS " if ok else "FAIL ") + os.path.basename(g))
        rc |= 0 if ok else 1
    sys.exit(rc)
