#!/usr/bin/env python3
"""Unit tests for the SCRIPTED hamlet generator (`hamletgen.py`, the 2026-08-11 experiment).

The DIVISION OF LABOR with the rest of the suite is deliberate and worth knowing before adding a
test here. The four demo maps in `pool/experiments/` are regenerated by `test_villages.py` on every
run and put through the whole gate, so the STAGES - the drawing, the placing, the manifest - are
covered end to end there, on real output, by the same machinery that covers every other pool map.
What this file covers is everything a map cannot: the pure derivations (sizing, rolls, geometry
helpers), the branches the four demos do not happen to take, and the failure modes that must stay
loud (a household count outside the tier band, a nonsense compass quarter).

So: a rule about SHAPE goes here; a rule about a MAP belongs in the pool.
"""

import math
import os
import sys
import tempfile

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import hamletgen as hg  # noqa: E402
from settlement import point_in_poly, seg_dist  # noqa: E402

# A unit square field envelope, big enough for the seat math to be readable.
SQUARE: list[tuple[float, float]] = [(400.0, 400.0), (1000.0, 400.0), (1000.0, 1000.0), (400.0, 1000.0)]


def a_plan(**kw: object) -> hg.SitePlan:
    """A plan with a known square field, for testing the derivations that read one."""
    spec = hg.HamletSpec(name="Test", seed=3, households=15, down_deg=90.0, windward="N", **kw)  # type: ignore[arg-type]
    plan = hg.plan_site(spec)
    plan.envelope = list(SQUARE)
    return plan


# ---- the spec refuses what the tier cannot draw --------------------------------------------------


@pytest.mark.parametrize("households", [0, 9, 21, 400])
def test_a_household_count_outside_the_hamlet_band_is_refused(households: int) -> None:
    """Below the band the place is an outlying farmstead; above it, it is a village and needs a
    headman, a shrine and tax-free plots this generator deliberately does not draw. Silently
    generating one anyway would produce a map that fails the gate for reasons that look unrelated."""
    with pytest.raises(ValueError, match="hamlet band"):
        hg.HamletSpec(name="X", seed=1, households=households)


def test_a_nonsense_compass_quarter_is_refused() -> None:
    with pytest.raises(ValueError, match="compass quarter"):
        hg.HamletSpec(name="X", seed=1, windward="NNW")


def test_an_unknown_water_sink_is_refused() -> None:
    with pytest.raises(ValueError, match="water_sink"):
        hg.HamletSpec(name="X", seed=1, water_sink="river")


# ---- sizing -------------------------------------------------------------------------------------


def test_the_field_target_is_gross_acres_times_households() -> None:
    plan = hg.plan_site(hg.HamletSpec(name="X", seed=1, households=15))
    assert plan.target_acres == pytest.approx(15 * hg.GROSS_ACRES_PER_HOUSEHOLD)


def test_the_canvas_grows_with_the_field_it_has_to_hold() -> None:
    small = hg.canvas_for(13.0, 1.0)
    big = hg.canvas_for(26.0, 1.0)
    assert big[0] > small[0] and big[1] > small[1]
    # ...and it is comfortably larger than the field, so `build_comb` never clamps the fan
    assert small[0] * small[1] > 13.0 * hg.SQ_FT_PER_ACRE * 2


@pytest.mark.parametrize(("households", "expect_last"), [(10, 0.93), (15, 0.93), (20, 0.93)])
def test_the_last_offtake_sits_near_the_canal_end(households: int, expect_last: float) -> None:
    """A supply canal running far past its last delivery ditch leaves a tail that dies in bare
    ground - see OFFTAKE_LADDER. Ikegami's authored 0.66 is exactly that shape of number."""
    a, _b = hg.offtakes_for(households)
    assert a[-1] == expect_last


def test_the_offtake_ladder_covers_counts_past_its_last_rung() -> None:
    assert hg.offtakes_for(999) == (hg.OFFTAKE_LADDER[-1][1], hg.OFFTAKE_LADDER[-1][2])


@pytest.mark.parametrize(("households", "wells"), [(10, 2), (12, 2), (15, 2), (20, 3)])
def test_wells_are_one_per_six_households_or_so(households: int, wells: int) -> None:
    """Inside `wells_sized_to_population`'s 2-20 households-per-well band at hamlet scale."""
    got = hg.well_target(households)
    assert got == wells
    assert 2 <= households / got <= 20


def test_a_tiny_hamlet_still_keeps_one_well() -> None:
    assert hg.well_target(1) == 1


# ---- the rolls ----------------------------------------------------------------------------------


def test_the_same_seed_plans_the_same_hamlet() -> None:
    one = hg.plan_site(hg.HamletSpec(name="X", seed=11, households=14))
    two = hg.plan_site(hg.HamletSpec(name="X", seed=11, households=14))
    assert (one.down_deg, one.windward, one.water_sink, one.cluster_shape, one.lane_skeleton) == (two.down_deg, two.windward, two.water_sink, two.cluster_shape, two.lane_skeleton)


def test_different_seeds_roll_different_hamlets() -> None:
    """The whole point of the knob layer: a cohort must not be twenty copies of one map."""
    combos = {(p.down_deg, p.water_sink, p.cluster_shape, p.lane_skeleton) for p in (hg.plan_site(hg.HamletSpec(name="X", seed=s, households=15)) for s in range(1, 21))}
    assert len(combos) >= 12


def test_every_declared_knob_is_honored_over_its_roll() -> None:
    plan = hg.plan_site(
        hg.HamletSpec(
            name="X",
            seed=5,
            households=13,
            down_deg=180.0,
            water_flow=95.0,
            windward="E",
            water_sink="offmap",
            cluster_shape="crescent",
            lane_skeleton="Y",
            plot_size="strip",
            grain_drift=12,
            woodland_patches=1,
        )
    )
    assert (plan.down_deg, plan.water_flow, plan.windward, plan.water_sink) == (180.0, 95.0, "E", "offmap")
    assert (plan.cluster_shape, plan.lane_skeleton, plan.plot_size, plan.grain_drift, plan.woodland_patches) == ("crescent", "Y", "strip", 12, 1)


def test_the_drainage_bearing_follows_the_fall_unless_declared() -> None:
    """A hamlet is one comb draining down one valley, so absent a declaration the two agree - but
    they stay separate fields, because at any larger tier they are genuinely different facts."""
    assert hg.plan_site(hg.HamletSpec(name="X", seed=2, down_deg=45.0)).water_flow == 45.0


@pytest.mark.parametrize("down_deg", [0.0, 45.0, 90.0, 135.0, 180.0, 225.0, 270.0, 315.0])
def test_the_cold_wind_comes_off_the_high_ground(down_deg: float) -> None:
    """Cold air drains downhill, so the wind a valley settlement shelters from blows from upslope
    (turned up to 45 deg). This is what makes 'back to the hill' and 'back to the wind' one fact
    rather than two, and rolling them apart put a cluster in the drainage ditch - see WIND_TURNS."""
    wx, wy = hg.WIND_VECTORS[hg.windward_for(down_deg, seed=4)]
    up = (-math.cos(math.radians(down_deg)), -math.sin(math.radians(down_deg)))
    assert wx * up[0] + wy * up[1] > 0.5  # within 60 deg of straight upslope


# ---- geometry helpers ---------------------------------------------------------------------------


def test_polygon_area_is_the_shoelace_area() -> None:
    assert hg.poly_area(SQUARE) == pytest.approx(600.0 * 600.0)


def test_acreage_is_measured_from_the_plots_not_the_envelope() -> None:
    """One 43,560 sq ft plot is one acre at 1 ft/px, and four of them are four - the conversion has
    to carry ftpx squared, which is the trap `build_comb`'s own `acres` falls into on a hamlet."""
    plot = [(0.0, 0.0), (220.0, 0.0), (220.0, 198.0), (0.0, 198.0)]  # 43,560 px^2
    assert hg.net_acres({"plots": [{"poly": plot}] * 4}, ftpx=1.0) == pytest.approx(4.0)
    assert hg.net_acres({"plots": [{"poly": plot}] * 4}, ftpx=2.0) == pytest.approx(16.0)


def test_centroid_and_unit() -> None:
    assert hg.centroid(SQUARE) == (700.0, 700.0)
    assert hg.unit(0.0, 0.0) == (0.0, 0.0)
    assert hg.unit(3.0, 4.0) == pytest.approx((0.6, 0.8))


def test_a_segment_through_a_polygon_is_detected() -> None:
    assert hg.crosses_poly((0.0, 700.0), (1400.0, 700.0), SQUARE)
    assert not hg.crosses_poly((0.0, 100.0), (1400.0, 100.0), SQUARE)


def test_a_segment_passing_near_a_disc_is_detected() -> None:
    assert hg.crosses_disc((0.0, 0.0), (100.0, 0.0), (50.0, 10.0), r=20.0)
    assert not hg.crosses_disc((0.0, 0.0), (100.0, 0.0), (50.0, 40.0), r=20.0)


def test_a_point_is_pulled_back_out_of_an_obstacle() -> None:
    inside = (700.0, 700.0)
    out = hg.pull_clear(inside, (200.0, 200.0), [SQUARE], margin=10.0, step=40.0)
    assert not hg.point_in_poly(out[0], out[1], SQUARE)


def test_pull_clear_gives_up_rather_than_looping_forever() -> None:
    """A point that cannot escape in the tries allowed is returned as it stands. The caller clamps
    to the canvas afterward, so a stuck point degrades the belt's shape - it does not hang."""
    huge = [(-1e5, -1e5), (1e5, -1e5), (1e5, 1e5), (-1e5, 1e5)]
    assert hg.pull_clear((0.0, 0.0), (1.0, 1.0), [huge], margin=10.0) is not None


def test_the_run_to_the_map_edge_is_measured_along_the_fall() -> None:
    plan = a_plan()  # falls due south
    assert hg.edge_run(plan, (500.0, plan.H - 300.0)) == pytest.approx(300.0)


def test_a_point_below_the_drain_is_recognized_as_wet_ground() -> None:
    drain = [(0.0, 1000.0), (2000.0, 1000.0)]  # runs east-west across a south-falling map
    assert hg.below_drain((1000.0, 1080.0), drain, 0.0, 1.0)  # downslope of it, in the toe band
    assert not hg.below_drain((1000.0, 900.0), drain, 0.0, 1.0)  # above it
    assert not hg.below_drain((1000.0, 1400.0), drain, 0.0, 1.0)  # past the toe band entirely


def test_ground_behind_a_margin_reports_how_much_of_it_is_crop() -> None:
    assert hg.back_fouled((700.0, 400.0), (0.0, -1.0), 100.0, []) == 0.0
    fouled = hg.back_fouled((700.0, 1000.0), (0.0, -1.0), 100.0, [SQUARE])  # normal points back INTO the square
    assert fouled > 0.5


# ---- the derivations that read the map ----------------------------------------------------------


def test_the_intake_sits_at_the_head_of_the_slope() -> None:
    """Gravity: a comb is fed from its high end. This was the first real bug in the experiment - the
    engine's canvas-relative `edge_*` anchors put a lateral intake at mid-height, which left the fan
    half a canvas to run and saturated the field far under the acreage the households needed."""
    plan = hg.plan_site(hg.HamletSpec(name="X", seed=6, households=15, down_deg=90.0))
    (sx, sy), name = hg.head_sluice(plan)
    assert sy < plan.H / 2  # upslope of the canvas middle on a south-falling map
    assert name.startswith("head_")


def test_the_cluster_is_seated_outside_the_field() -> None:
    plan = a_plan()
    seat = hg.seat_cluster(plan)
    assert not hg.point_in_poly(seat["cx"], seat["cy"], SQUARE)
    assert seat["lat"] > 0 and seat["dep"] > 0


def test_the_cluster_is_never_seated_below_the_drain() -> None:
    """The wet toe is not building ground. Excluded outright rather than scored down, because a
    strong enough wind score will otherwise pull the settlement into the bog."""
    plan = a_plan()
    drain = [(300.0, 1000.0), (1100.0, 1000.0)]  # along the square's low (south) edge
    seat = hg.seat_cluster(plan, drain=drain)
    assert seat["cy"] < 1000.0


def test_the_cluster_avoids_a_margin_whose_back_is_under_the_hem() -> None:
    """A margin hemmed by dry crop is not a worse seat, it is not a seat: the cluster's own band and
    the windbreak behind it would stand in the barley."""
    plan = a_plan()
    hem = [(400.0, 100.0), (1000.0, 100.0), (1000.0, 395.0), (400.0, 395.0)]  # the whole north back
    assert hg.seat_cluster(plan, dry_plots=[hem])["cy"] > hg.seat_cluster(plan)["cy"]


def test_a_field_with_no_buildable_flank_is_a_loud_error() -> None:
    plan = a_plan()
    boxed = [[(200.0, 200.0), (1200.0, 200.0), (1200.0, 1200.0), (200.0, 1200.0)]]  # crop on every side
    with pytest.raises(ValueError, match="no buildable flank"):
        hg.seat_cluster(plan, dry_plots=boxed)


def test_the_connector_track_leaves_the_frame_without_crossing_the_crop() -> None:
    """The guarantee is about the DRAWN path, not the straight line to its endpoint.

    This test used to assert the chord and is the reason it is worth spelling out: a track bows ~40
    px either side of its bearing, so chord and path disagree, and routing by the chord while
    drawing the bow is exactly how a connector came to be drawn through the rice with the router
    insisting it had checked."""
    plan = a_plan()
    plan.seat = hg.seat_cluster(plan)
    track = hg.connector_track(plan, (700.0, 200.0), avoid=[SQUARE])
    assert hg.path_violations(track, [SQUARE], None, []) == 0, "no segment of the drawn track may cross the crop"
    assert not (0 <= track[-1][0] <= plan.W and 0 <= track[-1][1] <= plan.H)  # ends off the canvas


def test_a_square_far_from_the_crop_clears_and_one_on_it_does_not() -> None:
    assert hg._clear_gap((700.0, 700.0), 50.0, [SQUARE], 1.0) is None  # standing in it
    assert hg._clear_gap((700.0, 200.0), 50.0, [SQUARE], 1.0) == pytest.approx(150.0)
    assert hg._clear_gap((700.0, 1100.0), 50.0, [SQUARE], 1.0) is None  # in the crop's sunny shadow
    assert hg._clear_gap((700.0, 700.0), 50.0, [], 1.0) is None  # no crop at all - nothing to measure


def test_a_square_near_a_line_is_detected() -> None:
    assert hg._near_line((100.0, 100.0), 20.0, [(0.0, 100.0), (200.0, 100.0)], pad=10.0)
    assert not hg._near_line((100.0, 400.0), 20.0, [(0.0, 100.0), (200.0, 100.0)], pad=10.0)


def test_the_report_line_names_the_map_and_its_verdict() -> None:
    plan = a_plan()
    assert "OK" in hg.Report(plan=plan, failures=[]).line()
    bad = hg.Report(plan=plan, failures=["a_check", "another"])
    assert not bad.ok and "FAIL" in bad.line() and "a_check" in bad.line()


# ---- end to end ---------------------------------------------------------------------------------


def test_a_pond_the_canvas_cannot_hold_falls_back_to_draining_OFF_MAP(monkeypatch: pytest.MonkeyPatch) -> None:
    """A CLAMPED pond is no pond, and the map must say so rather than draw one on the rice.

    `pond_setback` walks the tameike downslope until its rim clears the crop; the canvas clamp then
    pulls it back on-frame - and straight back onto the rice it had just cleared. The stage treats
    that as the same finding as a set-back past the limit and drains the field off the frame
    instead. Forced here by making the solver ask for a set-back the canvas cannot give, because no
    cohort seed currently produces one: the branch is real logic that the demo maps do not reach,
    which is exactly what this file is for."""
    # The set-back must pass the LIMIT test and still clamp - those are two different findings with
    # the same answer, and only the clamp is under test here.
    monkeypatch.setattr(hg, "POND_SETBACK_LIMIT", 1e9)
    monkeypatch.setattr(hg, "pond_setback", lambda plan, out, prx, pry, **kw: 5000.0)
    plan = hg.plan_site(hg.HamletSpec(name="Clamped", seed=23, households=12, water_sink="pond"))
    assert plan.water_sink == "pond", "the fixture must START as a pond map, or it proves nothing"
    s = hg.build(plan)
    assert plan.water_sink == "offmap", "a pond the canvas cannot hold must fall back to the off-map brook"
    assert not s.M.get("ponds"), "and no pond may be drawn"
    assert plan.sink_brook, "the fallback must actually cut the brook it promised"


def test_a_point_in_the_crop_is_pushed_out_on_the_LOCAL_edge_normal() -> None:
    """The defect the GM reported: a way's tip stopped 28 px INSIDE the paddy because it was pulled
    back along one fixed map-wide direction. The way out is the nearest OUTLINE EDGE's normal - and
    the nearest edge, not the nearest vertex, since a point deep in a lobe can have its nearest
    vertex round the far side."""
    square = [(0.0, 0.0), (100.0, 0.0), (100.0, 100.0), (0.0, 100.0)]
    out = hg.push_out_of(square, (90.0, 50.0), 10.0)  # nearest edge is the right one, x=100
    assert out == pytest.approx((110.0, 50.0))
    assert hg.push_out_of(square, (50.0, 5.0), 10.0) == pytest.approx((50.0, -10.0)), "the bottom edge is nearer here"
    far = hg.push_out_of(square, (300.0, 50.0), 10.0)
    assert far == (300.0, 50.0), "a point already clear is returned untouched - this must never drag a way back in"


def test_a_way_cutting_the_field_is_bent_ROUND_it_not_nibbled_at() -> None:
    """`route_around` walks the outline between where a leg enters and where it leaves.

    The first version inserted one waypoint at the mean of the crossings and re-ran; it converged a
    few px per round and ran out of rounds still crossing, because a point pushed off the middle of
    a lobe lands right beside the leg it came from. Both the detour and the odd-hit case (a leg that
    enters and does not leave) are asserted, and so is the do-nothing case."""
    square = [(0.0, 0.0), (100.0, 0.0), (100.0, 100.0), (0.0, 100.0)]
    bent = hg.route_around(square, [(-50.0, 50.0), (150.0, 50.0)], 8.0)
    assert len(bent) > 2, "a leg straight through the square must gain waypoints"
    for q in bent:
        assert not point_in_poly(q[0], q[1], square), f"{q} is still inside the crop"
    clear = [(-50.0, 200.0), (150.0, 200.0)]
    assert hg.route_around(square, clear, 8.0) == clear, "a way that never touches the field is left alone"
    stub = hg.route_around(square, [(50.0, 50.0), (150.0, 50.0)], 8.0)  # STARTS inside: one crossing, not two
    assert not point_in_poly(stub[0][0], stub[0][1], square)


def test_a_nonsense_field_archetype_is_refused() -> None:
    with pytest.raises(ValueError, match="field_archetype"):
        hg.HamletSpec(name="X", seed=1, field_archetype="terraces")


def test_the_roll_only_offers_archetypes_that_gate_clean() -> None:
    """`polder_grid` is opt-in until its own cohort is green (see ROLLED_ARCHETYPES).

    A rolled archetype with known failures mixes them into the valley tier's 36/36 and destroys the
    one number that says the scripted process is consistent - which is exactly what happened the
    moment the polder was added to the roll. Pinning it is still honoured; only the ROLL is held
    back, and this is the test that will fail (correctly) on the day someone promotes it."""
    assert set(hg.ROLLED_ARCHETYPES) <= set(hg.FIELD_ARCHETYPES)
    rolled = {hg.plan_site(hg.HamletSpec(name="X", seed=s, households=15)).field_archetype for s in range(1, 30)}
    assert rolled == set(hg.ROLLED_ARCHETYPES)


def test_a_polder_inlets_mouth_is_pulled_INSIDE_the_crop() -> None:
    """THE RATCHET for `draw_comb_field`'s constructed inlet end (2026-08-15).

    That end is not clipped from an anchor - it is BUILT, as the main channel's last point stepped
    70 px straight downhill, which is a COMB's geometry. On a polder the main is the ring canal
    running ALONG the high edge, so its last point is a corner and the step skims the boundary:
    seed 19 landed the mouth 2.6 px inside where `channel_field_anchored` wants 10, and no amount of
    moving the sluice changed it, because the anchor is not what sets this end.

    Seed 19 is chosen deliberately - it is the case that needed the pull (seed 3 needs it at 6.0 px,
    seed 8 does not need it at all), so this test exercises the branch rather than merely passing."""
    plan = hg.plan_site(hg.HamletSpec(name="Polder", seed=19, households=16, field_archetype="polder_grid", down_deg=90))
    s = hg.build(plan)
    with tempfile.TemporaryDirectory() as tmp:
        s.finish(os.path.join(tmp, "scratch"), render=False)
    env = [(float(a), float(b)) for a, b in s.M["fields"][0]["outline"]]
    n = len(env)
    fed = [c for c in s.M["channels"] if (c.get("to") or {}).get("kind") == "field"]
    assert fed, "the polder is fed by a channel from its header reservoir"
    for c in fed:
        end = c["poly"][-1]
        assert point_in_poly(end[0], end[1], env), f"the inlet mouth {end} must finish INSIDE the crop"
        gap = min(seg_dist(end[0], end[1], env[k], env[(k + 1) % n]) for k in range(n))
        assert gap >= 10.0, f"the mouth is {gap:.1f} px from the outline; the rule wants 10 so the field paints over it"


def test_a_polder_hamlet_draws_its_grid_dike_and_reservoir() -> None:
    """THE SECOND FIELD ARCHETYPE (GM 2026-08-13), pinned at what it currently guarantees.

    The polder is WORK IN PROGRESS - it has two named gate failures in `build_polder`'s own geometry
    (see hamletgen.md) - so this does not assert a clean gate, which would be a lie. It asserts the
    things the substrate is already responsible for and which no other test covers: that the grid is
    solved to the acreage the households imply, that every household is seated, that the defining
    perimeter dike exists, and that the header reservoir sits OUTSIDE the crop rather than in it,
    which two earlier versions of the siting got wrong in two different ways."""
    plan = hg.plan_site(hg.HamletSpec(name="Polder", seed=8, households=16, field_archetype="polder_grid"))
    assert plan.field_archetype == "polder_grid"
    s = hg.build(plan)
    with tempfile.TemporaryDirectory() as tmp:
        s.finish(os.path.join(tmp, "scratch"), render=False)
    assert s.M["meta"]["field_archetype"] == "polder_grid"
    assert abs(plan.acres - plan.target_acres) / plan.target_acres < 0.12, f"{plan.acres:.1f} acres against a {plan.target_acres:.1f} target"
    assert plan.placed == plan.spec.households
    assert s.M.get("dikes"), "a polder without its perimeter dike is not a polder"
    pond = s.M.get("pond")
    assert pond, "the header reservoir is the polder's water source"
    assert not point_in_poly(pond[0], pond[1], list(plan.envelope)), "the reservoir sits BESIDE the crop, never in it"


def test_a_rolled_cohort_passes_the_whole_gate() -> None:
    """The experiment's actual claim, in miniature, and a RATCHET on it.

    Hamlets rolled from seeds nobody looked at come out correct. The honest figure is still a pass
    RATE rather than a guarantee - a cohort of two dozen turns up the odd siting collision - so this
    pins the rate: a change that drops it fails here by name.

    The two things that hold WITHOUT exception, on every map whether it passes the gate or not, are
    asserted for all of them: the declared households are seated, and the paddy acreage lands on the
    figure the household count implies. Those are the derivations this module exists to get right.

    (The four demo maps in `pool/experiments/` carry the full-size version of the gate check, in
    `test_villages.py`; four members here keep the suite's runtime honest.)"""
    reports = hg.cohort(4, first_seed=41)
    assert len(reports) == 4
    for report in reports:
        assert report.plan.placed >= round(0.85 * report.plan.spec.households), f"{report.plan.spec.name} seated {report.plan.placed}/{report.plan.spec.households}"
        assert abs(report.plan.acres - report.plan.target_acres) / report.plan.target_acres < 0.15, (
            f"{report.plan.spec.name}: {report.plan.acres:.1f} acres against a {report.plan.target_acres:.1f} target"
        )
    # MEASURED 2026-08-12: 24 of 24 over the first two dozen seeds, and 4 of 4 here
    # (`python3 cohort_audit.py --count 24` reproduces the sweep and reports any residue by check).
    # It was 7 of 12 when the experiment was first reported. Keep this at 4 of 4: a change that drops
    # a single rolled hamlet now fails here by name, which is the whole point of a ratchet.
    passed = [r for r in reports if r.ok]
    assert len(passed) >= 4, f"only {len(passed)}/4 rolled hamlets pass the whole gate: " + "; ".join(f"{r.plan.spec.name}: {r.failures}" for r in reports if not r.ok)


def test_the_cli_reports_a_single_hamlet(tmp_path, capsys) -> None:  # type: ignore[no-untyped-def]
    out = str(tmp_path / "cli")
    # the RETURN CODE reports the gate's verdict on this particular seed, which is not what this
    # test is about - it is about the CLI writing the artifacts and reporting the map. Asserting a
    # green gate here would pin one arbitrary seed's luck (see the cohort ratchet above for the rate).
    hg.main(["--name", "Clitest", "--seed", "8", "--households", "11", "--down-deg", "90", "--sink", "offmap", "--windward", "N", "--out", out, "--no-render"])
    assert os.path.exists(out + ".json") and os.path.exists(out + ".svg")
    assert "Clitest" in capsys.readouterr().out


def test_the_cli_batch_mode_returns_nonzero_when_a_member_fails(monkeypatch, capsys) -> None:  # type: ignore[no-untyped-def]
    """The batch exit code is the experiment's pass/fail signal, so it has to be real."""
    monkeypatch.setattr(hg, "cohort", lambda n, first_seed=1: [hg.Report(plan=a_plan(), failures=["boom"])])
    assert hg.main(["--batch", "1"]) == 1
    assert "0/1 passed" in capsys.readouterr().out


def test_the_cli_batch_mode_returns_zero_when_every_member_passes(monkeypatch, capsys) -> None:  # type: ignore[no-untyped-def]
    monkeypatch.setattr(hg, "cohort", lambda n, first_seed=1: [hg.Report(plan=a_plan(), failures=[])])
    assert hg.main(["--batch", "1"]) == 0
    assert "1/1 passed" in capsys.readouterr().out


def test_the_cli_returns_nonzero_for_a_failing_single_map(monkeypatch, capsys) -> None:
    monkeypatch.setattr(hg, "generate", lambda spec, out_base=None, render=True: hg.Report(plan=a_plan(), failures=["boom"]))
    assert hg.main(["--name", "X"]) == 1
    assert "boom" in capsys.readouterr().out


def test_declared_knob_pins_reach_the_engine() -> None:
    """A `pins` entry is forwarded to the engine's own knob catalog, so a spec can steer a knob this
    module does not model (a land-use overlay, a field archetype)."""
    from settlement import Settlement

    plan = hg.plan_site(hg.HamletSpec(name="Pinned", seed=2, households=12, pins={"land_use_overlay": "lotus"}))
    s = Settlement(W=plan.W, H=plan.H, seed=plan.spec.seed)
    hg.stage_water_frame(s, plan)
    assert s.knob_pins["land_use_overlay"] == "lotus"


def test_a_fan_that_folds_back_on_itself_is_recognized() -> None:
    """The disqualifier `fit_field` uses: a hairpin in the fan's own ditch net."""
    straight = {"channels": [{"pts": [(0.0, 0.0), (100.0, 0.0), (200.0, 0.0)]}]}
    hairpin = {"channels": [{"pts": [(0.0, 0.0), (100.0, 0.0), (10.0, 5.0)]}]}
    assert not hg.net_bends_acutely(straight)
    assert hg.net_bends_acutely(hairpin)


def test_a_way_is_clipped_where_the_crop_begins() -> None:
    """`clip_to_clear` truncates rather than dragging a vertex, and returns NOTHING when the
    surviving run is too short to be a lane - the arm is simply not drawn."""
    assert hg.clip_to_clear([(0.0, 0.0), (100.0, 0.0)], [], 10.0) == [(0.0, 0.0), (100.0, 0.0)]
    clipped = hg.clip_to_clear([(0.0, 700.0), (900.0, 700.0)], [SQUARE], 10.0)
    assert clipped and max(p[0] for p in clipped) < 400.0
    assert hg.clip_to_clear([(395.0, 700.0), (900.0, 700.0)], [SQUARE], 10.0) == []


def test_a_shallow_crossing_is_distinguished_from_a_square_one() -> None:
    """A way may cross a ditch - that is what a plank is for - but not at a slant."""
    ditch = ((0.0, 0.0), (100.0, 0.0))
    assert not hg.shallow_crossing((50.0, -50.0), (50.0, 50.0), *ditch)  # square
    assert hg.shallow_crossing((0.0, -10.0), (100.0, 10.0), *ditch)  # a slant
    assert not hg.shallow_crossing((0.0, 100.0), (100.0, 100.0), *ditch)  # never meets it


@pytest.mark.parametrize(("down_deg", "start", "expect"), [(0.0, (500.0, 500.0), None), (180.0, (500.0, 500.0), 500.0), (90.0, (500.0, 500.0), None)])
def test_the_run_to_the_frame_is_measured_on_every_axis(down_deg, start, expect) -> None:  # type: ignore[no-untyped-def]
    """`edge_run` walks whichever axis the fall actually points along - east and west included, which
    the south-falling fixtures elsewhere in this file never exercise."""
    plan = hg.plan_site(hg.HamletSpec(name="X", seed=3, households=15, down_deg=down_deg))
    run = hg.edge_run(plan, start)
    assert run > 0
    if expect is not None:
        assert run == pytest.approx(expect)


def test_a_way_that_misses_the_watercourse_lands_on_nothing() -> None:
    """`crossing_lands_on_crop` answers about the CROSSING POINT, so a way that never meets the
    course has no crossing point and no verdict to give."""
    assert not hg.crossing_lands_on_crop((0.0, 0.0), (10.0, 0.0), (0.0, 50.0), (10.0, 50.0), [SQUARE])
    # ...and one that meets it inside the crop does
    assert hg.crossing_lands_on_crop((700.0, 300.0), (700.0, 900.0), (400.0, 700.0), (1000.0, 700.0), [SQUARE])


def test_a_pond_laid_over_the_crop_is_recognized() -> None:
    """The predicate `stage_sink` uses to check its own clamp: `pond_clear_of_field`'s two tests, on
    the same envelope, so the siting and the check cannot disagree."""
    plan = a_plan()
    assert hg.pond_clear_of_crop(plan, (700.0, 1400.0), 100.0, 60.0), "well below the field: clear"
    assert not hg.pond_clear_of_crop(plan, (700.0, 700.0), 100.0, 60.0), "sitting in the middle of it: not clear"
    assert not hg.pond_clear_of_crop(plan, (700.0, 1040.0), 100.0, 60.0), "rim overlapping the low edge: not clear"


def test_a_way_is_clipped_at_a_watercourse_as_well_as_at_a_crop() -> None:
    """A cluster's lane arms stop at the bank: they serve the houses, and a lane that crosses a ditch
    gets a deck sized for whatever angle it happens to meet the water at."""
    ditch = [((500.0, 0.0), (500.0, 400.0))]
    clipped = hg.clip_to_clear([(100.0, 200.0), (900.0, 200.0)], [], 10.0, lines=ditch)
    assert clipped and max(p[0] for p in clipped) < 500.0, "the arm must stop short of the water"
    assert hg.clip_to_clear([(100.0, 200.0), (300.0, 200.0)], [], 10.0, lines=ditch) == [(100.0, 200.0), (300.0, 200.0)], "a run that never reaches the water is untouched"
