#!/usr/bin/env python3
"""Kashikawa (樫川, "oak river") - the SCRIPTED hamlet at the top of the size band.

Generated by [`hamletgen.py`](../../hamletgen.py) rather than authored: this file declares a name, a
seed, a household count, the land's fall and where the runoff goes, and every position on the map -
the intake, the field's size, the cluster, the lanes, the connector track, the woods, the
windbreak - is derived from those by the pipeline. Nothing here is a coordinate.

The brief: 20 households - the ceiling of the hamlet band - on land falling northeast
(`down_deg=315`), the collector's brook running off the map (`water_sink="offmap"`). It exists to
show the pipeline at the top of the band, where the cluster, the well count and the paddy acreage
are all at their largest. See `kashikawa.notes.md` for the kanji triangle and the review log.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, SKILL)
from l7r.diagram.hamletgen import HamletSpec, generate  # noqa: E402

report = generate(HamletSpec(name="Kashikawa", seed=3, households=20, down_deg=315, water_sink="offmap"), out_base=os.path.join(HERE, "kashikawa"))
print(report.line())
