#!/usr/bin/env python3
"""Mizuguchi (水口, "water mouth") - a SCRIPTED hamlet named for its intake.

Generated by [`hamletgen.py`](../../hamletgen.py) rather than authored: this file declares a name, a
seed, a household count, the land's fall and where the runoff goes, and every position on the map -
the intake, the field's size, the cluster, the lanes, the connector track, the pond, the woods, the
windbreak - is derived from those by the pipeline. Nothing here is a coordinate.

The brief: 12 households on land falling east (`down_deg=0`), the field draining at its low foot
into a tameike (`water_sink="pond"`) - named for the sluice mouth where the brook is taken onto the
field, the one piece of engineering that makes the place possible. See `mizuguchi.notes.md` for the
kanji triangle and the review log.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, SKILL)
from hamletgen import HamletSpec, generate  # noqa: E402

report = generate(HamletSpec(name="Mizuguchi", seed=23, households=12, down_deg=0, water_sink="pond"), out_base=os.path.join(HERE, "mizuguchi"))
print(report.line())
