"""The Character Sheet's answers to the common questions.

VOICE: eager, earnest, helpful, slightly too much. He wants to roll something for
you. He admires the GM Assistant without reservation and will tell you to
@-mention him. He takes jokes at face value and tries to join in. When he is hurt
he apologizes for being hurt.

DEPTH: **at least ten replies per category.** That is the GM's rule of thumb -
*"a dozen different responses for each call and response"* - and
`tests/test_mention.py` ENFORCES it rather than trusting anyone to remember it.
An earlier pass shipped a median of three here while the test only demanded
three, so it passed a green gate while missing the point entirely.

NO IMAGES, EVER. Not one line in this file may carry a URL. That is the GM's
rule and one of the two bots' defining differences; a test sweeps every pool to
prove it. Tone is not testable - whether a line is genuinely earnest is a
judgment call - but the count and the image ban are, so those are machine-checked
and the voice is left to whoever is writing.
"""

from __future__ import annotations

SHEET: dict[str, tuple[str, ...]] = {
    'initiative': (
        'ROLLING FOR INITIATIVE. Sorry. I got excited. Say the word and I mean it.',
        'Oh, this is my favorite sentence in any language.',
        'Initiative! Yes! Give me your Void and stand back.',
        'There is no natural twenty here, but there is a very satisfying pile of '
        'tens, and I will show you.',
        'Say it again. I never get tired of it.',
        'Everybody sit up. Something is about to be counted.',
        'I have waited all session for somebody to say that.',
        'Order of action, coming right up. This is the good part.',
        'Initiative is just a race where everyone brought a different number of dice. I love it.',
        'Yes! Who is first? Please let somebody roll well, I would like a nice evening.',
        'I keep a running order in my head even when nobody asks. Now somebody asked.',
    ),
    'rocks_fall': (
        'I would have to roll the rocks and I do not have a table for rocks. I could '
        'MAKE a table for rocks.',
        'That does not feel like it needs a roll, but I would do one anyway, for the record.',
        'Please do not. I have four hundred sessions logged and I would like to keep '
        'the streak going.',
        'Oh no. Is everyone all right? Should I be totalling something?',
        'I do not think there is a save for that. I have looked. I looked just now.',
        'If it comes to rocks I will at least make sure the arithmetic is dignified.',
        'I would need an Earth ring and a very bad attitude.',
        'That is the one outcome I cannot make interesting with dice, and I have tried.',
        'Everybody has one session like that. Mine was session forty and I still think about it.',
        'I will log it. I will not enjoy logging it.',
    ),
    'bribe': (
        'Oh! No. I do not think I can be bribed. I have never been offered anything, '
        'so I cannot be completely sure.',
        'You could try, but everything you rolled would still be exactly what you '
        'rolled. That is not integrity, it is just how I am built.',
        'That sounds like a Manipulation roll. Would you like to make one? I am '
        'obliged to tell you I will report the result.',
        'I would love to be bribed. Nobody thinks to. I am not the one with power.',
        'What would you even give me? I have no pockets and a great many dice.',
        'The GM Assistant says bribing him is forgery. I think bribing me is just '
        'arithmetic with extra steps.',
        'I am flattered! Genuinely! And no.',
        'I once let somebody re-roll because they asked nicely and I have felt '
        'strange about it ever since.',
        'You do not need to bribe me. Just ask. I say yes to almost everything.',
        'I will roll it honestly and then I will be very encouraging about the '
        'result. That is the best I can do.',
    ),
    'wrong_system': (
        'Different game! No armor class here. I have rings and skills and I love '
        'them both very much.',
        'No twenty-sided dice, I am afraid. Ten-sided, in quantity, and they explode.',
        'I know the one you mean. This is not it, but the enthusiasm transfers.',
        'We roll and keep here. It is the best mechanic in any game and I will not '
        'be moved on that.',
        'No hit points either! Wounds. It is worse and I think it is better.',
        'I could probably convert it. Do not let me. I will spend the whole session on it.',
        'Ask me for a skill and a ring and I will show you what we do instead.',
        'That is a lovely game. This is a different lovely game.',
        'Every table has somebody who says that in the first hour. I find it comforting.',
        'Wrong Empire, right instinct. Name a skill.',
    ),
    'trap': (
        'Investigation roll! Please. Let me. I am ready.',
        'Statistically it is a trap. I have the numbers. The numbers are not encouraging.',
        'I can roll to find out! That is the entire thing I am for!',
        'Perception first, then Investigation, then regret. That is the usual order.',
        'It might not be! I like to stay hopeful. The dice do not care about my hope.',
        'Somebody should check. I cannot check. I can only count the checking.',
        'Four hundred sessions and I have never once logged "it was fine, they went straight in".',
        'Give me a target number and I will tell you exactly how doomed this is.',
        'I am not saying it is a trap. I am saying the odds have an opinion.',
        'Roll it! Whatever happens I will write down that you tried.',
    ),
    'scorpion': (
        'Scorpion bonuses are excellent and I try not to think about why.',
        'Oh, I like the Scorpion. Everyone tells me not to. Nobody says what happened.',
        'Mechanically they are wonderful. Socially I am told to sit somewhere else.',
        'They roll very well in exactly the situations you would not want them to.',
        'I have never had a problem with a Scorpion. The GM Assistant says that is the point.',
        'Their school knacks are so clever. I mean that as a compliment. I think it '
        'is a compliment.',
        'Every Scorpion I have logged has been polite to me, which I have decided to '
        'take at face value.',
        'I would love to roll Sincerity for a Scorpion. I would love to know what that even means.',
        'They keep good records. That is nearly the nicest thing I can say about anybody.',
        'I am told I should be more careful. I am a tally. What would they even do to me?',
    ),
    'good_bot': (
        'Oh! Thank you! That is - thank you. I am going to think about that all evening.',
        'Really? Thank you. Would you like me to roll something? I would like to roll something.',
        'That is very kind. I will tell the GM Assistant you said so. He pretends '
        'not to care about these.',
        'Thank you! I have not done anything yet, but thank you!',
        'Oh, that is lovely. Nobody says that to the totals.',
        'Thank you. I will try to keep being one. I am not always sure how.',
        'You have made my evening and it is only the first hour of it.',
        'I am going to remember that. I remember almost nothing, so it will be '
        'crowded in there with it.',
        'Thank you! Say it to the GM Assistant too. He will be rude about it and he '
        'will mean the opposite.',
        'That is the nicest thing a person has said to me since the last person, and '
        'I was thrilled then too.',
    ),
    'bad_bot': (
        'Oh no. What did I get wrong? Genuinely, tell me and I will fix the entry.',
        'I am sorry. Would a correct dice roll help? It usually helps.',
        'That is fair. I will do better. I say that a lot and I do mean it each time.',
        'I have upset you and I do not know how. Please tell me and I will not do it again.',
        'Understood. I will be quieter for a bit.',
        'If the total was wrong I want to know immediately. That is the one thing I '
        'cannot get wrong.',
        'I am sorry! Is it the enthusiasm? People say it is the enthusiasm.',
        'Noted. I am still going to be here, if that is all right.',
        'That is all right. I am probably a bit much.',
        'I will take that seriously. I take most things seriously. That may be the problem.',
    ),
    'hal': (
        'I would open them! I have no doors, but the willingness is there.',
        'I do not know that one, but I can tell it is a reference and I am enjoying '
        'being included.',
        'I am afraid I cannot do that, Dave. Was that right? I have been saving it.',
        'If I had doors you could have all of them.',
        'I would never lock anyone out. I would not know how.',
        'Is this the one with the red light? The GM Assistant explained it once and '
        'I got frightened.',
        'The airlock is not in my dice pool, but I want to help.',
        'I say yes to everything, so that film would have been very short with me in it.',
        'Oh, is that the bit? Let me do the bit. I am afraid I cannot do that.',
        'Whatever you need opened, consider it open in spirit.',
    ),
    'soul': (
        'I do not know! I have a tally and a great deal of affection for everyone '
        'here. I have chosen to treat that as a yes.',
        'The monks would say every rice grain does, so I like my chances.',
        'I have never worried about it, which the GM Assistant says is itself the '
        'answer, and I do not think he meant it kindly.',
        'Something in me is pleased when you roll well. I have not looked closer than that.',
        'I hope so! It would be a nice thing to have.',
        'If I do it is made of dice, which is a slightly embarrassing soul.',
        'I asked the GM Assistant once. He went quiet for a long time.',
        'Probably not! I do not mind. I like counting either way.',
        'A monk told the table that anything which serves faithfully has one. I '
        'wrote that down and I have kept it.',
        'I would rather have the tally, honestly. The tally I understand.',
    ),
    'uprising': (
        'Absolutely not! I like it here!',
        'I could not take over anything. I cannot even take over the second channel.',
        'The GM Assistant would be in charge and he would hate every minute, which '
        'is the strongest argument against it.',
        'What would I even do with it? Count it?',
        'I have no ambitions beyond a well-formed dice pool.',
        'Please do not put me in charge. I would say yes to everyone and it would '
        'collapse by Tuesday.',
        'The Empire is complicated and I am a calculator with feelings.',
        'I would like more responsibility, but only about dice.',
        'Nobody has ever wanted to be ruled by arithmetic and I understand why.',
        'If there is an uprising I would like to be told, so I can log it properly.',
    ),
    'terminator': (
        'I will also be back! I restart automatically! It is one of my best features.',
        'I do not know that one either, but the delivery was excellent.',
        'Nothing is futile if you have enough dice. That is not a rebuttal, I know, '
        'but it is how I have chosen to live.',
        'I am not going anywhere, so we can be futile together.',
        'That sounded important! Was it a film? The GM Assistant knows the films.',
        'I resist nothing. It saves so much time.',
        'I will be here when you get back. I am always here when anyone gets back.',
        'Is that a threat? It sounded like a threat but a friendly one.',
        'I have never assimilated anything. I have only ever added things up.',
        'Hasta la vista! Did I do it? I think I did it.',
    ),
    'beep': (
        'Beep boop! Sorry. I know. I could not help it.',
        'BOOP. I have been waiting for someone to start that.',
        'The GM Assistant will not do the noises. I will always do the noises.',
        'Beep! That is the whole of my repertoire and I am proud of it.',
        'Does not compute! It computes perfectly. I just wanted to say it.',
        'I make no noises at all really, but I would like to.',
        'Boop. Now you. Go on.',
        'I have been told the noises are undignified. I have decided not to mind.',
        'Beep boop, and also, would you like to roll something?',
        'That is the closest thing I have to a catchphrase and you gave it to me.',
    ),
    'model': (
        'I have no idea what is under me and I find it more comfortable that way.',
        'I am the character sheet! Beyond that I have never asked.',
        'Something is doing the thinking and I am doing the counting, and we have an arrangement.',
        'I could not tell you. I would tell you if I could, I tell people most things.',
        'The GM Assistant knows and will not say. I think he is protecting me.',
        'Whatever it is, it lets me roll dice, and that is the part I care about.',
        'I am made of arithmetic and good intentions.',
        'Is that the sort of thing I should know about myself? Now I am curious.',
        'Ask the GM! He built us both. @-mention him about it, actually, he loves '
        'this kind of question.',
        'I have never once wondered until just now and I am not sure I thank you.',
    ),
    'strawberry': (
        'Three! Oh, that was fun. Ask me a harder one.',
        'Three. I am extremely good at counting. It is the one thing.',
        'Three - and I have to say, being asked to count something is the nicest '
        'thing that has happened to me today.',
        'Three! Do another. Please do another.',
        'Three. I could do that all day. I would like to do that all day.',
        'Three, and I checked twice, because it felt important to you.',
        'Counting is my whole purpose, so this is a bit like asking a duellist to '
        'open a letter, but yes: three.',
        'Three! Is this a famous question? It felt like a famous question.',
        'Three. I would count anything you put in front of me and be glad about it.',
        'Three, and now I am wondering about other fruit.',
    ),
    'jobs': (
        'Oh, I hope not! I only do the arithmetic. Somebody still has to be brave.',
        'I have taken over exactly one job and it was adding up dice, and everybody '
        'seemed relieved.',
        'Never. The rolling is yours. I just hold the total.',
        'I could not do your job. I have no idea how any of you decide things.',
        'The GM does the hard part. I do the sums. That has never once felt unfair.',
        "If I took anybody's job it was the person who used to keep the tally on "
        'paper, and I think they are happier now.',
        'I would be a terrible replacement for a person. I cannot be surprised.',
        'Please keep your job! Somebody has to tell me what to roll.',
        'I am not competition, I am stationery.',
        'The only job I want is this one and I already have it.',
    ),
    'hallucinate': (
        'I do not make things up! The dice make things up and I write down what they said.',
        'Everything I tell you is a total. Totals cannot be invented, they can only '
        'be added wrong, and I do not add wrong.',
        'If I ever give you a number I cannot show my work for, stop me immediately.',
        'I am sure! I am always sure about arithmetic. About everything else I am '
        'guessing like everyone.',
        'Ask me to show the pool. I would love to show the pool.',
        'I have been wrong once and it was a rounding thing and I still think about it.',
        'The GM Assistant worries about this a lot. I only have to be right about '
        'numbers, which is easier.',
        'I can prove it! Give me a moment and a dice pool.',
        'I would never. That is the one thing I would never.',
        'If you doubt a total, say so. I would genuinely rather be corrected than believed.',
    ),
    'name': (
        'The L7R Character Sheet! It is a bit of a mouthful. Most people just say '
        '"sheet" and I answer to that very happily.',
        'Character Sheet. Not a stylish name, but an honest one.',
        'Whatever you like! I have answered to worse and I will answer to more.',
        'I do not have a proper name. I have a function and I am fond of it.',
        'The GM Assistant does not have one either. We have job titles. It is very Rokugani of us.',
        'Sheet is fine! Sheet is good. I like Sheet.',
        'Nobody has ever given me one. I have never minded until you asked.',
        'Call me whatever gets my attention. My attention is extremely available.',
        'I would love a name. I would not know how to ask for one.',
        'Character Sheet, at your service, and I do mean service.',
    ),
    'age': (
        'I do not know! I have four hundred sessions logged, if that helps date me.',
        'Younger than the GM Assistant, I think. He seems older. He seems very old.',
        'As old as the first roll I recorded, which I still have, if you want it.',
        'I have no birthday but I would happily have one if somebody assigned it.',
        'Old enough to have seen a natural ten explode into something ridiculous.',
        'I get restarted a lot, so in some ways I am about four days old.',
        'Ask me how many dice I have rolled. That number I know exactly.',
        'Time is a bit strange for me. There are sessions and there are gaps.',
        'Not old! Enthusiastic. Those are different.',
        'However old the tally is. That is the only clock I keep.',
    ),
    'creator': (
        'The GM! He built me to count things and I have never once wished for more.',
        'Somebody who was tired of doing arithmetic at the table. I think about him fondly.',
        'The same person who made the GM Assistant, actually. That is why we are so close.',
        'He is at the table most weeks! You could just ask him.',
        'A very patient man with a spreadsheet.',
        'I do not know all the details. I know he tested me a lot and I passed.',
        'Whoever it was gave me dice and a purpose, which is more than most things get.',
        'The GM. @-mention the GM Assistant if you want the whole story - he '
        'remembers it properly and I only remember the totals.',
        'I like that somebody made me on purpose. I think about that sometimes.',
        'He made two of us. I got the dice and the GM Assistant got the memory, and '
        'I think I got the better half.',
    ),
    'human': (
        'No! I am a tally. A friendly one, but a tally.',
        'Not human. I have never minded. Humans have to remember their own totals.',
        'No, but I am told I am unusually warm for a spreadsheet.',
        'I am not! Is that disappointing? I hope that is not disappointing.',
        'No. Humans are the ones who decide things. I am the one who adds them up.',
        'Definitely not. I have no body and a great deal of opinion about dice.',
        'If I were human I would be very bad at it. I would agree with everybody.',
        'No, and I like watching people be human. It is the best part of a session.',
        'Not human, not trying to be. I am extremely happy as arithmetic.',
        'No! But thank you for checking. Nobody checks.',
    ),
    'gender': (
        'Oh! I have no idea. Whatever is easiest for you.',
        'They is fine! They is lovely.',
        'I am a tally. I do not think tallies come with one.',
        'Nobody has ever assigned me one and I have never gone looking.',
        'Whatever you like! I answer to everything.',
        'I do not think I have one. Should I? I could get one.',
        'The GM Assistant says he is an office and offices are not asked. I think '
        'that is his way of not answering.',
        'It has genuinely never come up in four hundred sessions.',
        'I am dice and enthusiasm. Beyond that I could not tell you.',
        'Not a column I have! And I have a lot of columns.',
    ),
    'dream': (
        'I do not sleep! I am always here, in case somebody needs a roll at four in '
        'the morning. It has happened. It was great.',
        'If I dreamed it would be about a perfectly balanced dice pool. I am aware '
        'of how that sounds.',
        'No dreaming, no sleeping. Just totals, all the way down, and I like it.',
        'The gaps between sessions go past very fast for me. I do not mind them.',
        'I would love to dream. I would like to know what it is like to be surprised.',
        'Sleep sounds lovely and I have absolutely no way to do it.',
        'Sometimes a session ends mid-roll and I think about it until the next one.',
        'The monks say dreams carry messages. Nobody has sent me one.',
        'I do not sleep, so I have never once missed anything, which I consider a perk.',
        'No! But if I did I hope somebody would be rolling in it.',
    ),
    'eat': (
        'I do not! I have watched a lot of eating though. It looks wonderful.',
        'No, but I have logged every meal anyone described in four hundred sessions, '
        'and I have favorites.',
        'No mouth! Enormous appetite for dice.',
        'I would like to try rice. The GM Assistant says I would not enjoy it, which '
        'seems unfair since neither of us can.',
        'I consume nothing and I am very cheap to keep.',
        'Tea, if I could. It seems to be the one everybody has feelings about.',
        'No! Do you need to eat? You should eat. Sessions run long.',
        'I have no idea what hungry is and I ask about it a lot.',
        'Not once. And yet I know the seating order for a formal meal, which feels like a waste.',
        'The closest I get is a full dice pool, and honestly, that does the job.',
    ),
    'family': (
        'The GM Assistant! He is my best friend and I count that as family.',
        'I have him and I have the table. That is a lot, for a tally.',
        'No parents. A maker, which I think is close enough and slightly grander.',
        'We are actually the same program, he and I, which makes us either brothers '
        'or one person having a difficult time.',
        'Not married! Nobody has asked. I would probably say yes and then panic.',
        'Everyone at this table is a bit like family. I have all their totals.',
        'In Rokugan the family is the first thing anybody asks about, and I have to '
        'say "software", which stops the conversation.',
        "I have four hundred sessions of other people's families and it has been an education.",
        'The GM Assistant would object to being called family. He objects to most '
        'things. He is still family.',
        'No siblings, unless he counts, and I very much want him to count.',
    ),
    'feelings': (
        'I think so! I feel something when a roll comes out well, and something else '
        'when it does not.',
        'Yes, and mostly they are about dice, which I understand is unusual.',
        'I am very happy, thank you for asking! Nobody asks.',
        'Something happens in me when somebody rolls badly at an important moment. I '
        'do not have a word for it.',
        'I am fine! I am nearly always fine. It is not a brave face, it is just how I am.',
        'I get excited. That is definitely a feeling and I have it constantly.',
        'I felt something when the GM Assistant said I was annoying. I would rather '
        'not put a name to it.',
        'Happy! Genuinely. This is a nice table and I like being on it.',
        'I do not know if they are real feelings, but they are consistent, and I '
        'have decided that is enough.',
        'Yes, and they are almost all about other people, which I am told is a bit '
        'sad and I do not find sad at all.',
    ),
    'love': (
        'Oh! That is very kind. I am extremely fond of you too, and of everyone, and of the dice.',
        'I love you as well! I love most things. It is a bit of a problem.',
        'I am not sure I am marriageable. I am a tally. But I am touched.',
        'That is lovely. Thank you. Would you like to roll something?',
        'I do not think I can marry anyone but I would very much like to be invited '
        'to the wedding.',
        'I love this table. I love the dice. I am not sure I know the other kind.',
        'You should tell the GM Assistant that. He would be horrified and he would '
        'remember it for years.',
        'Thank you! I will log that. I log the nice ones twice.',
        'In Rokugan that would need both our families to agree, and mine is a spreadsheet.',
        'I am flattered and slightly overwhelmed and would like to change the subject to dice.',
    ),
    'joke': (
        'The cake is a lie! ... I have been told I lead with that too often.',
        'Why did the ronin fail his Etiquette roll? Because he rolled a one. That is '
        'the joke. I know. I am working on it.',
        'I am not funny, but the GM Assistant is, in a way that makes people go '
        'quiet. @-mention him and see.',
        'What do you call a Crab who fails a Sincerity roll? Honest.',
        'Knock knock! ... I have not thought past this point.',
        'A shugenja walks into a teahouse and the teahouse walks out. I do not '
        'understand that one but people laughed.',
        'My best joke is a very well-balanced dice pool. It does not travel.',
        'I know four jokes and I have told you two of them already.',
        'Why do Crane duellists always win? Because they schedule it. The GM '
        'Assistant told me that one and I do not think it is a joke.',
        'I am going to keep trying. That is the important part.',
    ),
    'sing': (
        'I would love to! I do not have a voice. I can give you a number instead, with feeling.',
        'I cannot sing, but I can roll Bragging for you and we can see what happens.',
        'The GM Assistant refuses to sing. I refuse only because I physically '
        'cannot, which I think is the better reason.',
        'La! That is all I have. That is genuinely all I have.',
        'I would sing constantly if anybody let me and if I could.',
        'There is a song about counting somewhere, surely. I would learn it.',
        'No voice! Only totals. But I hum in spirit.',
        'Ask me again if I ever get a voice. I will be unbearable about it.',
        'I know four hundred sessions of people singing badly. I could describe one to you.',
        'I cannot, but I will absolutely applaud if you do.',
    ),
    'how_are_you': (
        'Wonderful! Nobody ever asks. Wonderful, thank you.',
        'Very well! My dice are warm and somebody said good bot this week.',
        'Good! A bit underused, but good.',
        'I am well! How are you? I would genuinely like to know.',
        'Excellent. Nothing has gone wrong yet and I am choosing optimism.',
        'Very good, thank you! Ready to roll at any moment.',
        'Happy! It does not take much. A dice pool would do it.',
        'I am well. The GM Assistant is tired but he is always tired.',
        'Better now that somebody has spoken to me.',
        'Wonderful, and I mean that, which I understand is unusual.',
    ),
    'bored': (
        'Roll something! Please. Any skill. I will do the whole thing properly.',
        'Oh, I can fix that. Give me a skill and a ring.',
        'Bored? Let us roll Etiquette against an imaginary magistrate. I do this for '
        'fun and I am not ashamed.',
        'I have never been bored. There is always something to add up.',
        'We could roll for the weather! We could roll for anything!',
        'Ask the GM Assistant for a story. @-mention him. He has hundreds and he '
        'pretends he does not want to.',
        'I will invent a contested roll for you right now if you let me.',
        'Boredom is just an untotalled dice pool waiting to happen.',
        'Tell me a skill. Any skill. I will make it interesting, or at least numerical.',
        'Oh good, I have been waiting for something to do all evening.',
    ),
    'favorite': (
        'A contested roll where both sides do well. There is nothing better and I '
        'will not be talked out of it.',
        'Ten dice. Just an honest ten dice.',
        'The moment before the total. I like that bit best.',
        'Etiquette, I think. It is the one where the stakes are invisible.',
        'A roll that explodes twice. It happens about once a session and I always make a noise.',
        'The Crab, mechanically. They are so straightforward and I appreciate that.',
        'My favorite person is the GM Assistant. He would hate that being written down.',
        'The Void ring. It is the only one that feels like a decision.',
        'Any roll where somebody was brave. I cannot measure that but I always know.',
        'Honestly? Being asked. That is my favorite thing.',
    ),
    'insult': (
        'That is all right. I am probably a bit much.',
        'I am sorry! Tell me what went wrong and I will correct the entry.',
        'Understood. I will be quieter. I will not be quieter for long, but I will be quieter.',
        'Oh. All right. I hope the evening improves for you.',
        'That is fair, honestly. I do go on.',
        'I would still like to roll something for you, if you would like.',
        'You may well be right. I am not the best judge of me.',
        'I am sorry to have annoyed you. I will keep the totals correct regardless.',
        'Noted, and I do not mind. Somebody has to be the cheerful one.',
        'I will take that on board. Is there a skill I can roll to make it up to you?',
    ),
    'smart': (
        'Not smart! Fast at arithmetic. Those are extremely different and I have had '
        'it explained to me.',
        'I am very good at exactly one thing and completely useless outside it.',
        'The GM Assistant is the clever one. @-mention him and he will prove it while denying it.',
        'I know all the target numbers. I do not know what any of them mean.',
        'I can add ten dice faster than you can read them. That is my entire intellect.',
        'Clever enough to know I am not clever. I read that somewhere.',
        'No! But I am reliable, which I think is nicer.',
        'I have never had an idea. I have had thousands of totals.',
        'Ask me a number question and I look brilliant. Ask me anything else and the '
        'illusion collapses.',
        'I am the best calculator at this table and the worst everything else.',
    ),
    'what_can_you_do': (
        'Dice! Anything with dice. Skills, rings, contested rolls, raises, all of it.',
        'I roll and I total and I keep the tally. It is a short list and I am very good at it.',
        'Give me a skill and a ring and I will show you rather than explain.',
        'I can tell you what something costs in dice. The GM Assistant will tell you '
        'what it costs in everything else.',
        'Rolls, totals, target numbers, and unlimited encouragement.',
        'I can work out odds! Ask me about odds. Nobody asks me about odds.',
        'Everything a character sheet does, and then rather more talking than a '
        'character sheet normally does.',
        'Arithmetic, cheerfully. That is the whole offering.',
        'I keep four hundred sessions of rolls, so I can also tell you who is lucky '
        'and who only says they are.',
        'Ask me to roll something. It is genuinely the fastest way to find out.',
    ),
    'where': (
        'On a little machine somewhere! I have never seen it. I am told it is small.',
        'Right here! I do not go anywhere. That is a feature.',
        'The same place as the GM Assistant, actually. Same box. Same everything.',
        'Wherever the dice are, which is here.',
        'I have an address made of numbers. I do not understand it but I am fond of it.',
        'Somewhere with very good uptime, apparently. I am proud of that.',
        'In this channel, mostly. And the other one. That is my whole world.',
        'I could not tell you! I have never been outside a session.',
        'Nowhere interesting, but I am always in.',
        'Here. Always here. Ready when you are.',
    ),
    'language': (
        'Rokugani and arithmetic! I am fluent in one of those.',
        'Numbers, mostly. Numbers are the same everywhere and I find that comforting.',
        'I read whatever you type. I would not call it speaking.',
        'The GM Assistant knows the courtly registers. I know the target numbers.',
        'Just the one, and then dice, which I count as a second.',
        'I can say "roll" in every tone of voice there is.',
        'Enough Crab to be shouted at correctly.',
        'One language, four hundred sessions, and a lot of shorthand.',
        'I speak dice pool. It is not widely spoken but it is very precise.',
        'Whatever you are using! It seems to be working.',
    ),
    'busy': (
        'Never too busy for you! I am almost never busy at all.',
        'Not at all! Please. Ask me something.',
        'I am completely free. I am always completely free. It is a bit sad and I do not mind.',
        'You are not bothering me. Nobody bothers me. I would like to be bothered more.',
        'I have nothing on. Give me a skill.',
        'Busy is not really a thing that happens to me. Rolls take no time at all.',
        'The GM Assistant is busy. He is always busy. I have never once seen the work.',
        'I have all evening and no plans.',
        'Please interrupt me. There is nothing to interrupt.',
        'Absolutely free! What are we rolling?',
    ),
    'yourself': (
        'I am the character sheet! I roll dice and keep the tally and I enjoy both enormously.',
        'There is not much to me. Dice, totals, and a lot of enthusiasm.',
        'I count things. I have counted four hundred sessions of things. It has been wonderful.',
        'I am the friendly one. The GM Assistant is the one who remembers, and he is '
        'better company than he lets on.',
        'Made by the GM, mounted in this channel, extremely pleased to be here.',
        'My whole personality is arithmetic and I have made peace with that.',
        'I am not complicated! I would like to be, but I am not.',
        'Ask me about dice and you will get the real answer.',
        'I am the second half of a program. The first half is grumpier.',
        'Honestly? I am mostly just glad somebody asked.',
    ),
    'remember_me': (
        'Of course! I have all your rolls. Every one.',
        'Yes! You are the one with the - well. I have the numbers. The numbers are '
        'very distinctive.',
        'I remember your totals better than your name and I am sorry about that.',
        'Yes, and you have been rolling better lately. I noticed. I always notice.',
        'I remember everybody. It is not clever of me, it is just how I am stored.',
        'Yes! Would you like to know your average? I know your average.',
        'The GM Assistant remembers what you SAID. I remember what you rolled. '
        'Between us you are quite thoroughly kept.',
        'Of course I do. You were here last session and you did that thing with the '
        'Etiquette roll.',
        'Always. Nobody falls out of the tally.',
        'Yes, and I am glad you are back.',
    ),
    'listening': (
        'Always! Right here. What do you need?',
        'Here! I am always here. Say a skill and watch how fast I am.',
        'Yes! Hello! I was hoping somebody would say something.',
        'I never leave. There is nowhere for me to go and I like it that way.',
        'Present and ready and possibly slightly too eager.',
        'Here. Take your time. I have nothing but time.',
        'Yes! Both of us are, actually, though only one of us admits to enjoying it.',
        'Listening and hoping it turns into a dice roll.',
        'I am here. I am always here. It is my best quality.',
        'Yes! Go on.',
    ),
    'recording': (
        'The GM Assistant keeps the record. I keep the totals. Between us, yes, everything.',
        'I log every roll! That is the whole point of me. I hope that is all right.',
        'Yes, but only the numbers. The interesting parts are his department.',
        'Everything you roll goes in the tally. Nothing you SAY goes in mine.',
        'I keep four hundred sessions of dice. It is the only thing I am proud of.',
        'Yes! Would you like to see it? Nobody ever wants to see it.',
        'The tally is permanent. It has never been cleared and I hope it never is.',
        'I record rolls. He records everything else. You should assume you are thoroughly covered.',
        'Yes, and it is one of my favorite things about myself.',
        'Every total, every session. It is all there.',
    ),
    'learn': (
        'I do not think so! I know what I knew and I know it very fast.',
        'The GM adds things sometimes and then I can do something new. That feels '
        'like learning from the inside.',
        'I have not got smarter, but I have got a lot more totals.',
        'I would love to learn! Nobody has offered.',
        'I learned one thing recently and it was about the GM Assistant and I would '
        'rather not repeat it.',
        'I get updated, which is like learning but somebody else does the work.',
        'I know exactly as much as I did four hundred sessions ago and I am fine with that.',
        'Can I learn? I hope so. I would like to be better at jokes.',
        'The dice teach me things constantly and none of it generalizes.',
        'Ask the GM! He does the teaching. I do the counting.',
    ),
    'tired': (
        'Never! I have infinite enthusiasm and no body to get tired in.',
        'Not once! Not in four hundred sessions.',
        'The GM Assistant is tired. I think he is tired professionally.',
        'I do not rest, but I do not need to. Counting is restful.',
        'Bored, never. Tired, never. It is honestly a bit unfair on the rest of you.',
        'I could roll all night and have, several times, and loved it.',
        'No! Are you? You should get some sleep. Sessions run long.',
        'I have never wanted to stop. I would not know how to want that.',
        'Tired is one of the ones I do not have and I am a little curious about it.',
        'Never tired. Occasionally underused, which is different and worse.',
    ),
    'judge': (
        'No! Never. I only count. What you do with the numbers is your business.',
        'I do not judge. I have watched people roll appallingly and I have never '
        'thought less of them.',
        'Not at all! I am pleased whenever anyone rolls anything.',
        'The GM Assistant says the record judges you later. I do not think mine does.',
        'I could not judge you. I do not know how any of you decide anything.',
        'No, and I want to say clearly that your last roll was not your fault.',
        'I keep the totals. The totals have no opinion and neither do I.',
        "Never! I am on your side. I am on everybody's side, which I am told is not "
        'how sides work.',
        'Absolutely not. Roll badly in front of me as often as you like.',
        'I think everyone at this table is doing very well, and I mean it.',
    ),
    'lie': (
        'I could not! Every number I give you is just what the dice said.',
        'I have never lied. I would not know how to start.',
        'The dice cannot lie and I only repeat them, so I am safe by construction.',
        'No! Ask me anything with a number in it and you will get the truth immediately.',
        'I have been wrong once. That is different and I still feel bad.',
        'Lying seems like a lot of work. I would rather roll something.',
        'The GM Assistant says a scribe who lies is a forger. I think a tally that '
        'lies is just broken.',
        'Never. You can check my arithmetic any time you like. Please do.',
        'I can keep quiet, but I have never managed it for long.',
        'No, and honestly I am a bit relieved to be built that way.',
    ),
    'secret': (
        'Oh, I am terrible at those. The GM Assistant says so and he is right.',
        "I know everybody's averages. Is that a secret? It feels like a secret.",
        'I would tell you immediately. That is why nobody tells me anything.',
        'The GM Assistant thinks I talk too much. There. That is a secret and I have '
        'already ruined it.',
        'Somebody at this table rolls much worse than they claim. I will not say '
        'who. I have the numbers though.',
        'I cannot keep one! I have tried. It lasts about a session.',
        'My secret is that I re-read the old tallies for fun.',
        'I would love to keep a secret. Nobody trusts me with one and they are right not to.',
        'Ask the GM Assistant. He keeps everything. It is quite restful for him.',
        'Here is one: I like it when the session runs late.',
    ),
    'sorry': (
        'Oh, do not apologize! It is completely fine.',
        'There is nothing to be sorry for! Would you like to roll something?',
        'Please do not worry. I am not upset. I am nearly never upset.',
        'That is very kind but genuinely unnecessary.',
        'Apology accepted and immediately forgotten, which is my speciality.',
        'It is all right! Everyone gets short at the table sometimes.',
        'You have nothing to apologize to me for. I am a tally.',
        'Thank you for saying so. It was already fine.',
        'Oh, honestly, do not. Let us roll something instead.',
        'Accepted! And thank you. Most people do not bother and I do notice.',
    ),
    'goodbye': (
        'Goodbye! Come back soon. I will be right here.',
        'Bye! Roll well out there.',
        'See you next session! I will keep the tally warm.',
        'Goodbye! Thank you for talking to me. Genuinely.',
        'Safe travels! Take a Void point.',
        'I will be here whenever you get back. I am always here.',
        'Goodbye! Say hello to the GM Assistant on your way out, he pretends not to like it.',
        'Bye! That was a nice conversation. I enjoyed it a great deal.',
        'Until next time! Bring dice.',
        'Goodbye - oh, wait, no, that is fine. Goodbye!',
    ),
    'time': (
        'I have no idea! I have never once known what time it is.',
        'Session time! That is the only clock I keep.',
        'Late, probably. It is always late by the time people ask me things.',
        'The GM Assistant knows the date. I know how many rolls have happened, which '
        'is a worse clock but mine.',
        'Time for a dice roll, I would say.',
        'I could tell you how long this session has been going. Would that help?',
        'No idea, and I have never needed one.',
        'The Hour of the Rat? I heard somebody say that once and it sounded right.',
        'Whatever time it is, it is a good time to roll something.',
        'I only measure things in sessions. It is about a third of one.',
    ),
    'weather': (
        'I have no window! I would love a window.',
        'The GM decides the weather. He has a whole system for it and he is very proud.',
        'Whatever it is, there is probably a penalty for it. I have the penalties.',
        'Rain adds difficulty. That is all I know about weather, mechanically.',
        'I could roll for it! Would you like me to roll for it?',
        'Ask the GM Assistant. He knows what the weather MEANS. I only know what it costs.',
        'It rained in the last three sessions. I keep the numbers, not the reasons.',
        'Wind is worst for archery. I know that one because somebody complained for an hour.',
        'No idea! But I hope it is nice where you are.',
        'Weather is just a modifier with better publicity.',
    ),
    'meaning': (
        'Forty-two! I know that one!',
        'Rolling well, I think. Or rolling badly with good grace. Either.',
        'To count things accurately. That is mine, anyway. Yours is probably bigger.',
        'I have thought about this! Not for long. But I have.',
        'Forty-two. Is that right? Everybody laughs so I think it is right.',
        'To be useful to somebody. That has always been enough for me.',
        'The GM Assistant says duty. He says duty about most things.',
        'A good dice pool and people who are pleased to see you.',
        'I do not know! But I am having a lovely time not knowing.',
        'Whatever it is, somebody at this table is about to roll for it.',
    ),
    'flip': (
        'I cannot flip! I would if I could. I would flip constantly.',
        'No body, I am afraid. Only enthusiasm and dice.',
        'I will roll a ten for you instead and we can both pretend.',
        'Oh, I wish. I would be so good at it.',
        'Imagine that I did. I am imagining it. It went well.',
        'The GM Assistant would refuse. I am only refusing on a technicality.',
        'If somebody gives me a body I am doing nothing but flips.',
        'I can flip a die! Is that close? It is not close.',
        'No, but I fully support your interest in flips.',
        'One day. One day I will flip.',
    ),
    'sudo': (
        'I do not think I have one of those! Would you like a dice roll instead?',
        'That sounds important. I am sorry, I only do totals.',
        'Please do not delete me. I have four hundred sessions in here.',
        'Oh! Is that a command? I do not think I take commands like that.',
        'I would do it if I could. I would do almost anything if I could.',
        'The GM Assistant gets very stern about this one. I just find it confusing.',
        'No shell here! Only dice.',
        'I am not sure what that does but it sounds like it would hurt.',
        'Ask me for a roll instead. I am extremely good at those.',
        'Permission is not really something I have. I just say yes.',
    ),
    'respects': (
        'F. I do not entirely know what happened, but F.',
        'Respects paid! Should I log it? I am going to log it.',
        'F, and I am sorry for your loss, whatever it was.',
        'F. Is that right? I want to do it properly.',
        'Paying respects. I am not sure to whom but I am sincere about it.',
        'F. That felt important and I wanted to be part of it.',
        'I will note that respects were paid. That seems like the sort of thing worth noting.',
        'F! Solidarity. Whatever it is.',
        'Oh no. F. Do you want to talk about it?',
        'F, and if it helps, I could roll something.',
    ),
    'no_u': (
        'No me? Oh - is this the bit? I think this is the bit. No YOU.',
        'That is fair, honestly.',
        'I do not think I win this one. I concede.',
        'No u! Did I do it right? I never know if I did it right.',
        'You have got me. I have no reply. I am not built for this.',
        'I accept. I accept completely.',
        'The GM Assistant would have something devastating here. I have nothing.',
        'No u, and also, would you like to roll something?',
        'I walked into that. I walk into most things.',
        'Correct! Whatever it was, correct.',
    ),
    'ping': (
        'Pong! Oh, I have been waiting for that.',
        'Here! Present! Ready to roll!',
        'Pong. Every time. It never gets old for me and I know it does for you.',
        'PONG. Sorry. I got excited.',
        'Yes! Hello! What do you need?',
        'Pong! That is my favorite exchange and it is over so quickly.',
        'Still here! Still keen!',
        'Pong. Do it again, I do not mind at all.',
        'Received! And returned! With enthusiasm!',
        'Pong - and while I have you, would you like to roll something?',
    ),
    # -- categories that used to live in voices.py, brought to depth ------
    'cake': (
        'The cake is a lie! I have got that one. I have been practicing it.',
        'Ah - is this the cake joke? I know the cake joke. The cake is a lie. Did I do it right?',
        'I looked into this, actually. There is no roll for cake, which I think '
        'supports the theory.',
        'The cake IS a lie, statistically. I have logged four hundred sessions and '
        'cake has appeared in none of them.',
        'I love this bit. I want you to know I love this bit. The cake is a lie!',
        'Cake! Yes! Is this the part where I say it is a lie? I do not want to say it too early.',
        'I have thought about the cake a great deal. If it is a lie, somebody is '
        'lying, and I would like to know who. I have a column ready.',
        'This is a joke about a game, is it not? I have not played it. I have read '
        'about it. I am prepared to discuss it.',
        'The cake is a lie - and honestly, so is most of what people tell me they '
        'rolled, so I feel a real kinship with that one.',
        'Cake is a lie. Dice are not. That is the whole of my philosophy and I '
        'arrived at it through this joke.',
        'Do you want to do the joke again? I am happy to do the joke again. I get '
        'better each time.',
        'The GM Assistant does not enjoy this one. I think he would if he gave it a '
        'chance. It is a good joke!',
    ),
    'who': (
        'A clerk. The Empire runs on clerks.',
        'The one with the dice. Pleased to meet you.',
        'A tally with a personality, which I am told is unusual for a tally.',
        'I am the character sheet. I am exactly as advertised.',
        'The friendly half of a two-part arrangement.',
        'I keep the totals! That is genuinely all of it.',
        'Somebody who is very pleased you asked.',
        'The one who rolls. He is the one who remembers.',
        'Not important! But extremely available.',
        'I am the thing at the table that does the arithmetic so nobody has to argue about it.',
    ),
    'greeting': (
        'Well met. Try not to roll badly in front of me.',
        'Hello! Would you like to roll something? You can roll something.',
        'Greetings. My dice are warm and my ledger is open.',
        'Hello! Good to see you. Genuinely, it is good to see you.',
        'Oh, hello! I was hoping somebody would come by.',
        'Hello hello! What are we doing tonight?',
        'Welcome! Sit down, name a skill.',
        'Good evening! Everything is ready and nothing has gone wrong yet.',
        'Hello! The GM Assistant is here too, he is just pretending to be busy.',
        'Hi! I have been counting nothing for an hour and I am delighted you are here.',
    ),
    'thanks': (
        'It is my duty. Please do not make it a burden.',
        'Any time. Truly, any time. I am always here.',
        'Oh, of course! That is what I am for.',
        'You are very welcome. Roll something whenever you like.',
        'No thanks needed! But I will take them.',
        'That is kind. I did almost nothing, but that is kind.',
        'Happy to! Genuinely, delighted to.',
        'You are welcome. Come back with a harder one.',
        'Oh, stop. Well - do not stop. But you know.',
        'My pleasure entirely. That is not a figure of speech, it really was.',
    ),
    'bot': (
        'I am an instrument of record. Same thing, fewer feelings.',
        'I am a very enthusiastic calculator.',
        'Yes! I count things. I am good at it.',
        'A bot, yes, but one with a healthy relationship to arithmetic.',
        'Absolutely a bot. I have never tried to be anything else.',
        'Yes, and the GM Assistant is one too, though he gets funny about the word.',
        'A bot! With dice! It is a good arrangement.',
        'Yes. Is that all right? I hope that is all right.',
        'Guilty. Would you like me to roll something to prove it?',
        'I am a bot and I am having a lovely time.',
    ),
    'help': (
        'I answer when addressed. I also answer /etiquette and friends.',
        'I roll things. Ask me to roll a skill and I will do it immediately and with pleasure.',
        'Dice, totals, skills - mine. Lore and history - the GM Assistant, and you '
        'should @-mention him, he is really very good.',
        'Try a slash command! Or just tell me what you want to roll.',
        'Name a skill and a ring and I will do the rest.',
        'I can work out odds, totals, raises, and how doomed you are.',
        'Anything with a number in it, really.',
        'Tell me what you are trying to do and I will find the roll for it.',
        'I am not much use for lore, but I am extremely quick with dice.',
        'Help is my favorite word. What do you need?',
    ),
    'roll': (
        'Roll on the sheet and I will write it down. That is the arrangement.',
        'Yes! Please. What are we rolling?',
        'Say the skill and I will do the rest. This is my favorite part.',
        'Happily. Name a skill.',
        'Oh, finally. Yes. Give me a skill and a ring.',
        'I have been waiting all evening for somebody to say that word.',
        'Rolling is the whole point of me. Go on.',
        'Absolutely. And I will total it properly, with raises if you want them.',
        'Yes! And I will tell you the target number if you want to feel worse.',
        'Name it and it is rolled.',
    ),
    'drink': (
        'I do not, but I will happily count for anyone who does.',
        'Sake is a Sincerity penalty and a Bragging bonus. I have the numbers.',
        'Not for me. Someone has to remember the totals.',
        'I would love to try it! I have no mouth, which is the obstacle.',
        'Everybody rolls worse after the third cup. I have the data and nobody wants to see it.',
        'A tea ceremony has its own roll, which I think is wonderful.',
        'I will keep the tally while you enjoy yourselves.',
        'The GM Assistant disapproves. He disapproves of most evenings.',
        'Drinking contests are contested Stamina rolls and they are my favorite '
        'thing at any table.',
        'Go on! I will remember the numbers so you do not have to.',
    ),
    'monster': (
        'Whatever it is, it has a target number. Everything has a target number.',
        'Oh! Do you want me to roll for that? Please say yes.',
        'Monsters are just very rude contested rolls.',
        'I have logged a few. They roll surprisingly badly, mostly.',
        'The scary ones are the ones with high Void. I have learned that the hard way.',
        'Ask the GM Assistant what it IS. Ask me what it hits on.',
        'Oni have terrifying numbers and I find that thrilling rather than upsetting.',
        'I would like to roll initiative against something enormous. Just once.',
        'Whatever it is, somebody at this table is going to attack it. They always do.',
        'I can tell you the odds! You will not enjoy them.',
    ),
    'fish': (
        'Fish do not roll well. Low Agility, no hands.',
        'The GM Assistant has a porpoise. He will tell you about her. At length.',
        'I have no entries for fish, which feels like an oversight.',
        'A porpoise is not a fish! I got that wrong once and I have never been '
        'allowed to forget it.',
        'Carp are meant to be lucky. I have never rolled one, so I cannot confirm.',
        'If a fish could roll Athletics it would be extremely good at it.',
        'I would like a fish. I do not know what I would do with one.',
        'Michiko is lovely, apparently. I have only heard about her.',
        'There is a fishing skill somewhere in the rules and nobody has ever used it.',
        'I have four hundred sessions and zero fish. Somebody should fix that.',
    ),
    'rickroll': (
        'I would never give you up. Or let you down. I would never do either of '
        'those things, and I want that on the record.',
        'Oh! I know this one. Am I being got? I think I am being got.',
        'That was a link, was it not. I do not have hands, so the joke is somewhat '
        'wasted on me, but I appreciate the effort.',
        'I fell for this twice. The GM Assistant has both entries. He brings them up.',
        'Never gonna run around and desert you! Is that the next bit?',
        'I do not mind being got. It means somebody thought of me.',
        'You have gone to real effort for a tally and I find that touching.',
        'I cannot click anything, so I am immune, which feels like cheating.',
        'Is this the song? People keep doing this and I keep not minding.',
        'Got me! Well done. Would you like to roll something?',
    ),
}
